export type Source={id:string;title:string;publisher:string;date:string;kind:'官方'|'原始调查'|'机构样本';url:string;note:string};
export const sources:Source[]=[
{id:'F13',title:'Facebook Reels 发布接口与发布上限',publisher:'Meta for Developers',date:'2026-09-11读取官方正文',kind:'官方',url:'https://developers.facebook.com/docs/video-api/guides/reels-publishing/',note:'限Facebook Page；每Page滚动24小时30条API发布。初始化、上传、发布三步；本接口视频3–90秒，不能将App端规格直接套用。'},
{id:'F14',title:'Graph API / Pages API 限流规则',publisher:'Meta for Developers',date:'2026-09-11读取官方正文',kind:'官方',url:'https://developers.facebook.com/docs/graph-api/overview/rate-limiting/',note:'Page/System User token使用BUC规则：24小时调用数=4,800×Page互动用户；另受CPU/时间限制。App token的200×用户/小时是另一口径。'},
{id:'F15',title:'Video Insights：Reels指标与权限',publisher:'Meta for Developers',date:'2026-09-11读取；页面版本v26.0',kind:'官方',url:'https://developers.facebook.com/docs/graph-api/reference/video/video_insights/',note:'公布Reels播放、重播、时长、留存、关注、互动字段；Reels表未列收藏。要求Page ANALYZE、pages_manage_engagement及read_insights；具体账号返回待联调。'},
{id:'Y17',title:'YouTube API 当前配额表',publisher:'Google Developers',date:'2026-09-11核查；当前正文',kind:'官方',url:'https://developers.google.com/youtube/v3/determine_quota_cost',note:'项目默认上传100次/日、搜索100次/日、其他接口合计10,000单位/日；分桶。页面自动摘要仍有旧成本数字，以正文和方法页为准。'},
{id:'Y18',title:'频道每日上传上限',publisher:'YouTube Help',date:'动态帮助页；2026-09-11核查',kind:'官方',url:'https://support.google.com/youtube/answer/10383400?hl=en',note:'单频道24小时限额覆盖网页、移动端及API，随地区/历史等变化；官方未给统一条数。'},
{id:'Y19',title:'videos.list 批量查询与调用成本',publisher:'Google Developers',date:'动态接口文档；2026-09-11核查',kind:'官方',url:'https://developers.google.com/youtube/v3/docs/videos/list',note:'每次调用1单位；id支持多个视频，读取statistics及contentDetails等字段；实际短时配额看项目控制台。'},
{id:'Y20',title:'Analytics 数据时效与配额',publisher:'Google Developers',date:'2026-09-11更新/核查',kind:'官方',url:'https://developers.google.com/youtube/analytics/data_model',note:'通常延迟48–72小时；每次查询1单位，具体配额在项目控制台。不能套用Google Analytics网站统计API限额。'},
{id:'Y21',title:'Analytics 观看、时长与收藏替代指标',publisher:'Google Developers',date:'动态指标文档；2026-09-11核查',kind:'官方',url:'https://developers.google.com/youtube/analytics/metrics',note:'观看分钟、平均观看秒数、互动及增减订阅；videosAddedToPlaylists含稍后观看，是加入次数而非独立收藏人数。'},
{id:'Y22',title:'视频统计字段及口径',publisher:'Google Developers',date:'动态接口文档；2026-09-11核查',kind:'官方',url:'https://developers.google.com/youtube/v3/docs/videos',note:'viewCount/likeCount/commentCount；favoriteCount已废弃且恒为0，不能表示收藏。视频文件时长不等于用户观看时长。'},
{id:'Y23',title:'订阅者通知频率限制',publisher:'YouTube Help',date:'动态帮助页；2026-09-11核查',kind:'官方',url:'https://support.google.com/youtube/answer/7389684?hl=en',note:'每位观众每频道24小时最多3次视频/直播/首映通知；短时批量发布可能暂停通知24小时，非上传条数上限。'},
{id:'Y24',title:'发布频次与观看表现',publisher:'YouTube Help',date:'动态帮助页；2026-09-11核查',kind:'官方',url:'https://support.google.com/youtube/answer/141805?hl=en',note:'官方未要求日更；研究未发现跨上传观看增长与上传间隔相关。不能按发片倍数直接推定流量倍数。'},
{id:'Y25',title:'Analytics 查询参数与批量过滤',publisher:'Google Developers',date:'动态接口文档；2026-09-11核查',kind:'官方',url:'https://developers.google.com/youtube/analytics/reference/reports/query',note:'视频过滤可列至多500个ID；可组合指标及按video分组。分页、维度兼容与频道授权分别约束。'},
{id:'Y26',title:'Analytics 最新口径与收益权限变更记录',publisher:'Google Developers',date:'2026-09-09条目；09-11核查',kind:'官方',url:'https://developers.google.com/youtube/analytics/revision_history',note:'澄清48–72小时延迟；收入数据需YPP及monetary scope；公开播放口径与收益资格口径不同。'},
{id:'Y16',title:'YouTube 手机号验证限额',publisher:'YouTube Help',date:'动态帮助页；2026-09-11核查',kind:'官方',url:'https://support.google.com/youtube/answer/171664?hl=en',note:'同一手机号每年最多关联验证2个频道；高级功能仍需频道历史或可用的ID/视频验证。'},
{id:'F11',title:'Facebook 主档案身份与多档案',publisher:'Meta Newsroom',date:'2023-09-21；历史公告',kind:'官方',url:'https://about.fb.com/news/2023/09/you-can-now-have-multiple-personal-profiles-on-facebook/',note:'主档案使用日常姓名；不得冒充或虚报身份。公告中的附加档案功能限制不能直接当作当前规则。'},
{id:'F12',title:'Facebook Page 访问权限',publisher:'Facebook Help',date:'2026-09-11核查；官方索引可读，直接页需登录',kind:'官方',url:'https://www.facebook.com/help/289207354498410/',note:'Facebook访问与任务访问分开；可通过Business Suite等管理。完全控制者可移除其他人或删除Page。'},
{id:'Y9',title:'多个频道与 Brand Account 管理',publisher:'YouTube Help',date:'动态帮助页；2026-09-11核查',kind:'官方',url:'https://support.google.com/youtube/answer/4642409?hl=en',note:'同一Google账号可管理多个Brand Account频道；频道可有独立名称与身份。'},
{id:'Y10',title:'频道权限与角色限制',publisher:'YouTube Help',date:'动态帮助页；2026-09-11核查',kind:'官方',url:'https://support.google.com/youtube/answer/9481328?hl=en',note:'无需共享Google密码；Editor可上传发布。受邀用户的频道权限不支持YouTube APIs。'},
{id:'Y11',title:'高级功能、频道历史与身份验证',publisher:'YouTube Help',date:'动态帮助页；2026-09-11核查',kind:'官方',url:'https://support.google.com/youtube/answer/9891124?hl=en',note:'电话验证后，以频道历史或可用的ID/视频验证解锁高级功能；按后台完成验证或积累频道历史。高级功能不等于YPP获批。'},
{id:'Y12',title:'虚假互动政策',publisher:'YouTube Help',date:'动态政策页；2026-09-11核查',kind:'官方',url:'https://support.google.com/youtube/answer/3399767?hl=en',note:'人为增加观看、订阅及互订违规；正常引导关注和评论允许。委托推广者的行为也可能影响频道。'},
{id:'Y13',title:'Promote 与 YPP 资格统计',publisher:'YouTube Help',date:'动态帮助页；2026-09-11核查',kind:'官方',url:'https://support.google.com/youtube/answer/12199105?hl=en',note:'通过Promote获得的订阅及观看小时不计YPP资格；不能以广告购买准入指标。'},
{id:'Y15',title:'YouTube API 上传与审核限制',publisher:'Google Developers',date:'动态API文档；2026-09-11核查',kind:'官方',url:'https://developers.google.com/youtube/v3/docs/videos/insert',note:'2020-07-28后创建且未验证的API项目，上传视频限为私密；解除限制需通过API合规审核。'},
{id:'F5',title:'Reels Play 历史奖励上限',publisher:'Meta Newsroom',date:'2022-02-22',kind:'官方',url:'https://about.fb.com/news/2022/02/launching-facebook-reels-globally/',note:'历史计划最高35,000美元/月；是有条件的上限，不是人均，不作为2026收益报价。'},
{id:'F6',title:'Ads on Reels 转向按表现付费',publisher:'Meta Newsroom',date:'2023-05-09',kind:'官方',url:'https://about.fb.com/news/2023/05/expanding-ads-on-reels/',note:'当时邀请制、地区要求、接受条款及收款设置；从广告展示收入转向内容表现，旧计划条件仅作历史对照。'},
{id:'F7',title:'Facebook 视频统一为 Reels',publisher:'Meta Newsroom',date:'2025-06-17',kind:'官方',url:'https://about.fb.com/news/2025/06/making-it-easier-create-videos-facebook/',note:'逐步将所有新视频统一按Reels分享；长短视频均包括，不能把Reels付款全算为短视频付款。'},
{id:'F8',title:'重复分发、虚假互动与收益限制',publisher:'Meta Newsroom',date:'2025-04-24；页面另含10-22日期',kind:'官方',url:'https://about.fb.com/news/2025/04/cracking-down-spammy-content-facebook/',note:'垃圾账号网络、无关文案及操纵互动可能失去推荐和变现资格；不能以批量分发数量替代账号质量。'},
{id:'F9',title:'Content Monetization 详细准入及付款条款入口',publisher:'Meta Business Help Center',date:'2026-09-11访问：跳转登录，全文未核实',kind:'官方',url:'https://www.facebook.com/business/help/1049081556813520',note:'待核验：最低年龄、地区/语言、最低计佣时长及付款细则；官方页需登录。'},
{id:'F10',title:'Stars 门槛下调与账号成长工具',publisher:'Meta Newsroom',date:'2023-06-14；历史公告',kind:'官方',url:'https://about.fb.com/news/2023/06/helping-creators-get-discovered-and-earn-money-on-facebook/amp/',note:'当时将Stars降至500粉丝、30天；这是粉丝打赏工具的条件，不能当作Reels播放收益准入；当前完整资格另核。'},
{id:'Y8',title:'YouTube 收入分成与付款时间',publisher:'YouTube Help',date:'动态帮助页',kind:'官方',url:'https://support.google.com/youtube/answer/72902?hl=en',note:'观看页广告净收入55%；粉丝付费净收入70%；Shorts为分配池45%；符合付款条件时一般每月21–26日发放。'},
{id:'Y1',title:'YPP 当前完整广告准入',publisher:'YouTube Help',date:'动态政策页',kind:'官方',url:'https://support.google.com/youtube/answer/72851?hl=en',note:'1,000 订阅＋4,000 小时/12个月，或1,000万Shorts/90天；须审核。'},
{id:'Y2',title:'扩展 YPP 与支持地区',publisher:'YouTube Help',date:'动态政策页',kind:'官方',url:'https://support.google.com/youtube/answer/13429240?hl=en',note:'500订阅＋3次公开上传＋3,000小时或300万Shorts；各变现功能另有资格。'},
{id:'Y3',title:'YPP 准入调整（2027-02-01起）',publisher:'YouTube Help',date:'2027-02-01 生效',kind:'官方',url:'https://support.google.com/youtube/answer/12843009?hl=en',note:'新申请8,000小时或2,000万Shorts，仍需1,000订阅；Shorts池持续收益需90天1,000万合格观看。'},
{id:'Y4',title:'Shorts 收益政策',publisher:'YouTube Help',date:'动态政策页',kind:'官方',url:'https://support.google.com/youtube/answer/12504220?hl=en',note:'按合格Engaged views分配，保留所分配创作者池的45%；签署模块前观看不追溯。'},
{id:'Y5',title:'频道内容变现政策',publisher:'YouTube Help',date:'页面含2025-07-15更新',kind:'官方',url:'https://support.google.com/youtube/answer/1311392?hl=en',note:'原创、非实质重复；即使有授权，仍可能不符合重复使用内容变现政策。'},
{id:'Y6',title:'AI 内容披露',publisher:'YouTube Help',date:'动态政策页',kind:'官方',url:'https://support.google.com/youtube/answer/14328491?hl=en',note:'需要披露的合成内容应标注；不能将AI工具使用直接等同于禁赚。'},
{id:'Y7',title:'YouTube Shopping 联盟准入',publisher:'YouTube Help',date:'动态政策页',kind:'官方',url:'https://support.google.com/youtube/answer/13376398?hl=en',note:'YPP、支持地区、非音乐合作伙伴、非主要儿童内容；试点资格可能不同。'},
{id:'F1',title:'Facebook 2025付款、邀请制与 Fast Track',publisher:'Meta Newsroom',date:'2026-03-18',kind:'官方',url:'https://about.fb.com/news/2026/03/creator-fast-track-grow-your-audience-earn-money-on-facebook/',note:'2025年近30亿美元；Content Monetization仍邀请制；Fast Track为有条件的3个月计划。'},
{id:'F2',title:'Facebook 2024 合并变现计划',publisher:'Meta Newsroom',date:'2024-10-02',kind:'官方',url:'https://about.fb.com/news/2024/10/monetize-content-facebooks-new-streamlined-program/',note:'过去一年超过20亿美元；400万是2017年以来累计获收入人数，不能用来计算当年人均。'},
{id:'F3',title:'Facebook 原创内容规则',publisher:'Meta Newsroom',date:'2026-03-12/13（页面显示两日期）',kind:'官方',url:'https://about.fb.com/news/2026/03/rewarding-original-creators-on-facebook/',note:'页面所有者制作内容及有实质贡献内容；小幅改动、重复上传会影响推荐与收益。'},
{id:'F4',title:'Facebook 与 Amazon、Shopee 等联盟合作',publisher:'Meta Newsroom',date:'2026-03-25',kind:'官方',url:'https://about.fb.com/ltam/news/2026/03/llega-una-nueva-era-de-descubrimiento-de-productos-impulsada-por-ia-y-los-creadores/',note:'美国Amazon/eBay/Temu、亚洲Shopee等合作扩展；公告不等于每个账户都获得入口或固定触达。'},
{id:'A1',title:'美国 Associates 标准佣金表',publisher:'Amazon Associates',date:'动态费率页',kind:'官方',url:'https://affiliate-program.amazon.com/help/node/topic/GRXPHT8U84RAYDXZ',note:'品类费率0%–10%；此表不适用于所有国家或特殊活动。'},
{id:'A2',title:'美国 Associates 申请审核',publisher:'Amazon Associates',date:'动态规则页',kind:'官方',url:'https://affiliate-program.amazon.com/help/node/topic/G8TW5AE9XL2VX9VM',note:'180天3笔合格销售；通常500自然粉丝、约10条原创内容是审核参考，不是保证录取。'},
{id:'A3',title:'Creator Connections 活动设置',publisher:'Amazon Ads',date:'2026-05-12；官方索引可读，正文动态加载',kind:'官方',url:'https://advertising.amazon.com/help/GMANECFAFD49W23Y',note:'活动预算下限5,000美元、额外佣金≥10%、周期30–365天；预算非入驻费。'},
{id:'A4',title:'Creator Connections 双方资格',publisher:'Amazon Ads',date:'动态规则页；官方索引可读，正文动态加载',kind:'官方',url:'https://advertising.amazon.com/help/GPARAL6JVGFEJKG2',note:'US广告账户（主体位于US/CN/HK）、品牌角色；创作者需Influencer及Bronze+；按活动卖家SKU归因。'},
{id:'A5',title:'联盟计佣、归因与 Creator Ads Boost',publisher:'Amazon Associates',date:'2026-04-14 更新',kind:'官方',url:'https://affiliate-program.amazon.com/help/operating/policies',note:'合格净收入与会话条件；Ads Boost需获邀及同意，可授权Amazon将内容用于广告，未保证流量数量。'},
{id:'A6',title:'额外佣金叠加与活动预算',publisher:'Amazon Associates',date:'指南含2024–2025活动示例；官方PDF索引可读',kind:'官方',url:'https://f.media-amazon.com/images/G/01/Associates/Marketing/CreatorConnections/Amazon_Creator_Connections_Getting_Started_Guide.pdf',note:'额外佣金可叠加普通佣金；预算由所有参与创作者共同消耗；受活动和合格已发货销售条件限制。'},
{id:'A7',title:'Amazon 卖家注册材料',publisher:'Sell on Amazon',date:'动态指南',kind:'官方',url:'https://sell.amazon.com/sell/registration-guide?mons_sel_locale=en_US',note:'身份、企业、地址、银行及税务等注册核验；类目要求另外核对。'},
{id:'A8',title:'联盟关系披露',publisher:'Amazon Associates',date:'动态帮助页',kind:'官方',url:'https://affiliate-program.amazon.com/help/node/topic/GZTM7NTSEHMGH2DR',note:'明确披露联盟关系及使用规定的Associate身份说明。'},
{id:'S1',title:'Shopee 马来西亚 Facebook 联盟',publisher:'Shopee Help MY',date:'动态帮助页',kind:'官方',url:'https://help.shopee.com.my/portal/10/article/185732',note:'18+、Shopee Affiliate、Page/专业档案、原创且真实内容；按商品/活动计佣，确认且未退款后结算。'},
{id:'S2',title:'Shopee 马来西亚联盟服务费',publisher:'Shopee Help MY',date:'2025-06-08 生效',kind:'官方',url:'https://help.shopee.com.my/portal/10/article/177386',note:'已核定佣金收1%服务费，费用另加8%SST；YouTube Shopping佣金排除；RM500→RM494.60。'},
{id:'L1',title:'2022 Creator Report',publisher:'Linktree',date:'2022报告；2021年调查',kind:'原始调查',url:'https://linktr.ee/creator-report/',note:'n=9,576 Linktree用户；全职46%年收入<1,000美元，12%>50,000美元。'},
{id:'L2',title:'2023 Creator Report',publisher:'Linktree',date:'2023报告；回顾12个月',kind:'原始调查',url:'https://linktr.ee/creator-report-23/',note:'72%收入<500美元；该收入题有效样本数及分母细节未清楚披露，不能当平台人口普查。'},
{id:'C1',title:'State of Creator Marketing 2024–2025',publisher:'CreatorIQ / Sapio',date:'2024–2025报告，第27、51–53页',kind:'原始调查',url:'https://www.creatoriq.com/hubfs/TheStateofCreatorMarketing2024-2025_Pr.pdf',note:'平均月收入2,100美元；创作者子样本231人，主账号粉丝>1,000，73%兼职，以欧美为主。'},
{id:'C2',title:'State of Creators 2026',publisher:'CreatorIQ / Influencers.club',date:'2026-05-29至06-29调查，回顾上一年',kind:'原始调查',url:'https://www.creatoriq.com/whitepaper/state-of-creators',note:'n=5,095、100国；收入档占比67/14/8/6/3/1%；跨平台总内容收入。'},
{id:'C3',title:'2025 Creator Earnings Report',publisher:'Cookie Finance',date:'2026-02-11发布；2025财务数据',kind:'机构样本',url:'https://cookiefinance.co/resources/blog/2025-creator-earnings-report-what-1000-full-time-creators-reveal-about-the-creator-economy/',note:'1,000+样本且年收入≥60,000美元；YouTube组年收入中位141,000美元，包含多种收入。'},
{id:'R1',title:'2025 Shorts RPM 国家样本',publisher:'AIR Media-Tech',date:'2025-07-14更新；机构原文索引可读',kind:'机构样本',url:'https://air.io/monetization/what-rpm-can-you-expect-from-shorts-in-2025',note:'机构数千频道样本；ID .012 / PH .023 / US .328 / CA .165美元每千观看；未公开各国样本数与加权方法。'},
{id:'T1',title:'YouTube 2022 付款披露',publisher:'Think with Google',date:'2022-09-28',kind:'官方',url:'https://business.google.com/ca-en/think/marketing-strategies/short-and-long-form-videos/',note:'过去3年支付500亿美元；所引用正文是50 billion，不写成精确逐年支付。'},
{id:'T2',title:'YouTube 2024 美国影响力报告发布',publisher:'YouTube Blog',date:'2025-06-10',kind:'官方',url:'https://blog.youtube/news-and-events/2024-us-youtube-impact-report/',note:'正文另列2021–2023年全球创作者、艺人及媒体公司付款超过700亿美元；GDP贡献不等于收入。'},
{id:'T3',title:'YouTube 2026 CEO 信',publisher:'YouTube Blog',date:'2026年CEO信',kind:'官方',url:'https://blog.youtube/inside-youtube/the-future-of-youtube-2026/',note:'过去4年超过1,000亿美元，不能视为2025单年。'},
{id:'P1',title:'广告背书与商业关系披露',publisher:'美国 FTC',date:'2019指南；现行官方页面',kind:'官方',url:'https://www.ftc.gov/business-guidance/resources/disclosures-101-social-media-influencers',note:'商业关系须清楚披露；视频不能只在描述藏披露；不得虚构体验或无证据产品效果。'}
];
export const income=[{label:'低收入',annual:'不足 $10,000',monthly:'不足 $833',share:67},{label:'中等 · 较低段',annual:'$10,000–25,000',monthly:'约 $833–2,083',share:14},{label:'中等 · 中间段',annual:'$25,001–50,000',monthly:'约 $2,083–4,167',share:8},{label:'中等 · 较高段',annual:'$50,001–100,000',monthly:'约 $4,167–8,333',share:6},{label:'高收入',annual:'$100,001–250,000',monthly:'约 $8,333–20,833',share:3},{label:'更高收入',annual:'超过 $250,000',monthly:'超过 $20,833',share:1}];
export const rpm=[{name:'印度尼西亚',value:.012},{name:'菲律宾',value:.023},{name:'美国',value:.328},{name:'加拿大',value:.165}];
export const rates=[{name:'不计佣品类，例如礼品卡、酒类',rate:0},{name:'食品、健康及个人护理',rate:1},{name:'电视、数字电子游戏',rate:2},{name:'电脑及组件、DVD',rate:2.5},{name:'家居、家具、普通美妆、宠物用品',rate:3},{name:'服装、鞋、包、手表',rate:4},{name:'厨房用品、实体书、汽车用品',rate:4.5},{name:'音乐、Handmade、数字视频',rate:5},{name:'指定奢侈美妆',rate:10}];
export const history=[
['2022报告','2021调查','Linktree，全平台内容收入','46%全职年收入不足$1,000；12%超过$50,000','9,576名用户；不是平台分成','L1'],
['2023报告','回顾过去12个月','Linktree，全平台内容收入','72%不足$500；17%为$500–5,000；5%为$5,000–10,000；6%超过$10,000','收入题样本数/分母细节未清楚披露；证据权重较低','L2'],
['2024–2025报告','报告标注的调查期间','CreatorIQ / Sapio','平均月收入$2,100；月均数×12=$25,200','231名创作者；73%兼职；并非东南亚样本','C1'],
['2026-02发布','2025财务数据','Cookie Finance，成熟职业群体','YouTube组年收入中位数$141,000；÷12=$11,750','全样本1,000+；入样年收入≥$60,000；非纯广告收入','C3'],
['2026调查','2026年5–6月调查，回顾上一年','CreatorIQ / Influencers.club','67%年收入<$10,000；各档比例见图','5,095名，100国；非平台专属平均','C2']
];
export const payouts=[['YouTube','2022-09披露','过去3年','$500亿','创作者经济付款；非Shorts专项','T1'],['YouTube','2025-06披露','2021–2023','$700亿以上','创作者、艺人、媒体公司','T2'],['YouTube','2026 CEO信','过去4年','$1,000亿以上','滚动4年，与前行窗口重叠','T3'],['Facebook','2024-10披露','过去1年','$20亿以上','视频、Reels、图文等','F2'],['Facebook','2026-03披露','2025日历年','接近$30亿','同比+35%；60%流向Reels（含长短视频）','F1']];
export const checks=[
{title:'账号与经营授权',need:'商户身份、店铺主体、Page/频道管理授权',action:'核对主体一致性；授予发布所需角色，补齐授权范围。',refs:'A7'},
{title:'素材与音乐权利',need:'原文件、版权或商用许可、人物/品牌授权',action:'确认覆盖Facebook/YouTube及商业推广；缺件退回补齐或替换。',refs:'Y5,F3'},
{title:'商品与落地页一致',need:'ASIN/SKU、型号、规格、美国站链接、配送信息',action:'核对视频与实际购买商品一致，检查有效库存与目标地区。',refs:'A3,A4'},
{title:'价格、优惠与有效期',need:'现价、优惠条件、适用人群、起止日期',action:'删除过期价格；发布前再次确认，避免将有条件优惠写成普惠。',refs:'A5,P1'},
{title:'宣传和体验可证实',need:'功能/认证/效果的支撑材料',action:'删除无依据效果承诺；不能把商家素材写成运营方虚构的亲测。',refs:'P1'},
{title:'广告和联盟披露',need:'合作关系、佣金关系、必要免责声明',action:'适用的广告背书在视频及可见文案清晰披露；补上联盟身份说明。',refs:'A8,P1'},
{title:'链接和佣金归属',need:'账户、追踪链接、商品费率及活动条款',action:'核对登记推广渠道、追踪参数、活动卖家SKU、周期和预算。',refs:'A2,A4,A6'},
{title:'发布与结算记录',need:'商户确认稿、发布URL、后台点击/销售/佣金记录',action:'记录版本和发布时间；按后台最终合格销售及佣金对账。',refs:'A4,S1'}
];
