import "reflect-metadata";
import assert from "node:assert/strict";
import { randomUUID, randomBytes } from "node:crypto";
import { readFile, readdir } from "node:fs/promises";
import { before, after, test } from "node:test";
import { Pool } from "pg";
import { NestFactory } from "@nestjs/core";
import type { INestApplication } from "@nestjs/common";
import { participationProtocolVersion, participationRunSchema, participationChallengeSchema, participationReceiptSchema, contractVersion } from "@socialgrowth/product-contracts";
import { AppModule } from "./app.module.js";
import { ProductExceptionFilter } from "./product-exception.filter.js";
import { InstallationAuthService } from "./installation-auth-service.js";
import { LocalParticipationService, loadCurrentLocalParticipation } from "./local-participation-service.js";
import { PhoneControlJournal } from "./phone-control-journal.js";
const url=process.env.SG_PRODUCT_TEST_DATABASE_URL, cluster=process.env.SG_PRODUCT_TEST_CLUSTER_ID;
if(!url || !cluster || process.env.SG_PRODUCT_TEST_ALLOW_RESET!=="1" || new URL(url).hostname!=="127.0.0.1" || new URL(url).pathname!=="/sg_participation5_component") throw new Error("Owned isolated participation component database required");
const pool=new Pool({connectionString:url,max:8}), s="socialgrowth_product", pepper="synthetic-participation-component-pepper-001";
const auth=new InstallationAuthService(pool,pepper), service=new LocalParticipationService(pool,auth), journal=new PhoneControlJournal(pool);
let app:INestApplication, base:string;
async function guard(){const r=(await pool.query("select current_database() db,system_identifier::text cluster from pg_control_system()")).rows[0];assert.equal(r.db,"sg_participation5_component");assert.equal(r.cluster,cluster);}
before(async()=>{await guard();await pool.query(`DROP SCHEMA IF EXISTS ${s} CASCADE`);const dir=new URL("../migrations/",import.meta.url);for(const f of (await readdir(dir)).filter(f=>/^\d{4}.*\.sql$/.test(f)).sort()) await pool.query(await readFile(new URL(f,dir),"utf8"));
process.env.SG_PRODUCT_DATABASE_URL=url;process.env.SG_PRODUCT_AUTH_PEPPER=pepper;process.env.SG_PRODUCT_SMS_MODE="unavailable";process.env.SG_PRODUCT_MATERIAL_MODE="unavailable";delete process.env.SG_PRODUCT_DEVELOPMENT_SMS_TOKEN;
app=await NestFactory.create(AppModule,{logger:false});app.useGlobalFilters(new ProductExceptionFilter());await app.listen(0,"127.0.0.1");base=await app.getUrl();});
after(async()=>{try{await app?.close();await guard();await pool.query(`DROP SCHEMA IF EXISTS ${s} CASCADE`);}finally{await pool.end();}});
const input=(runId:string,extra:Record<string,unknown>={})=>({protocolVersion:participationProtocolVersion,requestId:`request-${randomUUID()}`,requestKey:`pulse-${randomUUID()}`,runId,...extra});
async function fixture(){const a=await auth.bootstrap({metadata:{contractVersion,requestId:`request-${randomUUID()}`,idempotencyKey:`bootstrap-${randomUUID()}`},installationCredential:`sginst_v1_${randomBytes(32).toString("base64url")}`},`source-${randomUUID()}`);
const deviceId=randomUUID(),providerId=randomUUID(),associationId=randomUUID(),associationSessionId=randomUUID();
await pool.query(`INSERT INTO ${s}.providers(provider_id,phone_e164,display_name,status) VALUES($1,$2,'Synthetic client','active')`,[providerId,`+86${Math.floor(1e10+Math.random()*8e10)}`]);
await pool.query(`INSERT INTO ${s}.devices(device_id,display_name,state) VALUES($1,'Synthetic participation phone','associated_pending_access')`,[deviceId]);
await pool.query(`INSERT INTO ${s}.association_sessions(association_session_id,installation_id,expected_installation_generation,device_label,code_digest,expires_at) VALUES($1,$2,1,'Synthetic association',$3,clock_timestamp()+interval '1 hour')`,[associationSessionId,a.installation.installationId,randomBytes(32)]);
await pool.query(`INSERT INTO ${s}.device_associations(association_id,device_id,installation_id,provider_id,association_session_id) VALUES($1,$2,$3,$4,$5)`,[associationId,deviceId,a.installation.installationId,providerId,associationSessionId]);
await journal.initialize(deviceId,randomUUID(),`init-${randomUUID()}`);return{token:a.sessionToken,installationId:a.installation.installationId,sessionId:a.session.sessionId,deviceId,providerId,runId:randomUUID()};}
type Fixture=Awaited<ReturnType<typeof fixture>>;
async function pulse(f:Fixture){await service.start(f.token,input(f.runId));const c=await service.challenge(f.token,input(f.runId));return service.confirm(f.token,input(f.runId,{challengeId:c.challengeId}));}
async function current(f:Fixture,now=new Date()){const c=await pool.connect();try{return await loadCurrentLocalParticipation(c,f.deviceId,now);}finally{c.release();}}
async function post(path:string,token:string,body:unknown,scheme="Bearer"){const r=await fetch(`${base}/api/installation/participation/${path}`,{method:"POST",headers:{authorization:`${scheme} ${token}`,"content-type":"application/json"},body:JSON.stringify(body)});return{status:r.status,body:await r.json() as unknown,cache:r.headers.get("cache-control")};}
test("real HTTP installation routes persist challenge and confirmation without action permission or stop proof",async()=>{const f=await fixture();const start=await post("start",f.token,input(f.runId));assert.equal(start.status,201);assert.equal(start.cache,"no-store");participationRunSchema.parse(start.body);
const c=await post("challenge",f.token,input(f.runId));assert.equal(c.status,201);const challenge=participationChallengeSchema.parse(c.body);
const r=await post("confirm",f.token,input(f.runId,{challengeId:challenge.challengeId}));assert.equal(r.status,201);const receipt=participationReceiptSchema.parse(r.body);assert.equal(receipt.actionPermissionGranted,false);assert.equal(receipt.stopConfirmed,false);assert.deepEqual(await current(f),receipt);assert.equal((await journal.read(f.deviceId)).disposition,"stop_requested");});
test("wrong bearer, forged scope and unassociated installation cannot confirm participation",async()=>{const f=await fixture();assert.equal((await post("start",f.token,input(f.runId),"Provider")).status,401);assert.equal((await post("start",f.token,input(f.runId,{scope:{deviceId:f.deviceId}}))).status,400);
await pool.query(`UPDATE ${s}.device_associations SET ended_at=clock_timestamp() WHERE device_id=$1`,[f.deviceId]);await assert.rejects(service.start(f.token,input(f.runId)));});
test("replay retains original challenge expiry and confirmation time; new challenge retains prior fresh pulse",async()=>{const f=await fixture();await service.start(f.token,input(f.runId));const request=input(f.runId),c=await service.challenge(f.token,request);assert.deepEqual(await service.challenge(f.token,{...request,requestId:`request-${randomUUID()}`}),c);
const r=await service.confirm(f.token,input(f.runId,{challengeId:c.challengeId}));assert.deepEqual(await service.confirm(f.token,input(f.runId,{challengeId:c.challengeId})),r);await service.challenge(f.token,input(f.runId));assert.deepEqual(await current(f),r);assert.equal(await current(f,new Date(Date.parse(r.validUntil))),null);});
test("expired nonce, superseded nonce and wrong run cannot manufacture a new pulse",async()=>{const f=await fixture();await service.start(f.token,input(f.runId));const c=await service.challenge(f.token,input(f.runId));await service.challenge(f.token,input(f.runId));await assert.rejects(service.confirm(f.token,input(f.runId,{challengeId:c.challengeId})));
const next=await service.challenge(f.token,input(f.runId));const now=new Date(Date.now()-7000);await pool.query(`UPDATE ${s}.local_participation SET challenge=$2 WHERE device_id=$1`,[f.deviceId,{...next,issuedAt:now.toISOString(),expiresAt:new Date(now.getTime()+6000).toISOString()}]);await assert.rejects(service.confirm(f.token,input(f.runId,{challengeId:next.challengeId})));assert.equal(await current(f),null);});
test("withdrawal atomically increments control generation, blocks late heartbeat and preserves stopped=false",async()=>{const f=await fixture();await pulse(f);const c=await service.challenge(f.token,input(f.runId)),before=await journal.read(f.deviceId);const r=await service.withdraw(f.token,input(f.runId));assert.equal(r.state,"withdrawn");assert.equal(r.stopConfirmed,false);assert.equal(r.scope.controlGeneration,(BigInt(before.controlGeneration)+1n).toString());assert.equal(await current(f),null);
await assert.rejects(service.confirm(f.token,input(f.runId,{challengeId:c.challengeId})));await assert.rejects(service.challenge(f.token,input(f.runId)));await assert.rejects(service.start(f.token,input(f.runId)));});
test("old withdrawn run cannot revoke successor; simultaneous run starts leave only one active run",async()=>{const f=await fixture();await pulse(f);const withdrawn=await service.withdraw(f.token,input(f.runId));const next={...f,runId:randomUUID()};await pulse(next);const before=await journal.read(f.deviceId);assert.deepEqual(await service.withdraw(f.token,input(f.runId)),withdrawn);assert.deepEqual(await journal.read(f.deviceId),before);assert.ok(await current(next));
const ids=[randomUUID(),randomUUID()];await Promise.all(ids.map(id=>service.start(f.token,input(id))));const rows=(await pool.query(`SELECT run_id FROM ${s}.local_participation_runs WHERE device_id=$1 AND revoked_at IS NULL`,[f.deviceId])).rows;assert.equal(rows.length,1);assert.ok(ids.includes(rows[0].run_id));});
test("fact, epoch, owner and installation replacement immediately invalidate participation",async()=>{for(const kind of ["fact","epoch","owner","installation"]){const f=await fixture();await pulse(f);
if(kind==="fact")await pool.query(`UPDATE ${s}.devices SET fact_version=fact_version+1 WHERE device_id=$1`,[f.deviceId]);
if(kind==="epoch")await journal.apply(f.deviceId,(await journal.read(f.deviceId)).version,`stop-${randomUUID()}`,{kind:"request_stop",stopRequestId:randomUUID()});
if(kind==="owner")await pool.query(`UPDATE ${s}.providers SET status='disabled' WHERE provider_id=$1`,[f.providerId]);
if(kind==="installation")await pool.query(`UPDATE ${s}.installations SET status='replaced',generation=generation+1 WHERE installation_id=$1`,[f.installationId]);
assert.equal(await current(f),null);await assert.rejects(service.challenge(f.token,input(f.runId)));}});
test("disabled owner may withdraw but cannot renew; revoked session cannot authenticate",async()=>{const f=await fixture();await pulse(f);await pool.query(`UPDATE ${s}.providers SET status='disabled' WHERE provider_id=$1`,[f.providerId]);assert.equal((await service.withdraw(f.token,input(f.runId))).state,"withdrawn");
const other=await fixture();await pulse(other);await pool.query(`UPDATE ${s}.installation_sessions SET revoked_at=clock_timestamp() WHERE session_id=$1`,[other.sessionId]);assert.equal(await current(other),null);await assert.rejects(service.challenge(other.token,input(other.runId)));});
test("reauthentication after lock wait rejects session that expired while queued",async()=>{const f=await fixture();await service.start(f.token,input(f.runId));await pool.query(`UPDATE ${s}.installation_sessions SET expires_at=clock_timestamp()+interval '300 milliseconds' WHERE session_id=$1`,[f.sessionId]);const c=await pool.connect();await c.query("BEGIN");await c.query(`SELECT provider_id FROM ${s}.providers WHERE provider_id=$1 FOR UPDATE`,[f.providerId]);const pending=service.challenge(f.token,input(f.runId));await new Promise(r=>setTimeout(r,500));await c.query("COMMIT");c.release();await assert.rejects(pending);assert.equal(await current(f),null);});
test("audit failure rolls back withdrawal and control revocation together",async()=>{const f=await fixture();await pulse(f);const before=await journal.read(f.deviceId);await pool.query(`CREATE FUNCTION ${s}.deny_participation_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='local_participation.withdraw' THEN RAISE EXCEPTION 'fixture'; END IF; RETURN NEW; END $$; CREATE TRIGGER deny_participation_audit BEFORE INSERT ON ${s}.audit_records FOR EACH ROW EXECUTE FUNCTION ${s}.deny_participation_audit()`);
try{await assert.rejects(service.withdraw(f.token,input(f.runId)));assert.deepEqual(await journal.read(f.deviceId),before);assert.ok(await current(f));}finally{await pool.query(`DROP TRIGGER deny_participation_audit ON ${s}.audit_records; DROP FUNCTION ${s}.deny_participation_audit()`);}});
test("heartbeats keep one mutable row and create no repeated start/withdraw audits",async()=>{const f=await fixture();await pulse(f);for(let i=0;i<6;i++){const c=await service.challenge(f.token,input(f.runId));await service.confirm(f.token,input(f.runId,{challengeId:c.challengeId}));}
const r=(await pool.query(`SELECT (SELECT count(*)::int FROM ${s}.local_participation WHERE device_id=$1) slots,(SELECT count(*)::int FROM ${s}.audit_records WHERE object_id=$1 AND action LIKE 'local_participation.%') audits`,[f.deviceId])).rows[0];assert.deepEqual(r,{slots:1,audits:1});});
