import assert from "node:assert/strict";
import { randomUUID,randomBytes,createHash,generateKeyPairSync } from "node:crypto";
import { readFile,readdir } from "node:fs/promises";
import { before,after,test } from "node:test";
import { Pool } from "pg";
import { contractVersion,executionLibraryVersion,controlProtocolVersion,participationProtocolVersion,artemisPreparationAssignmentSchema,type PhoneActionRequest } from "@socialgrowth/product-contracts";
import { InstallationAuthService } from "./installation-auth-service.js";
import { OperatorAuthService } from "./operator-auth-service.js";
import { AccountPreparationService } from "./account-preparation-service.js";
import { LocalParticipationService } from "./local-participation-service.js";
import { PhoneControlJournal } from "./phone-control-journal.js";
import { PostgresArtemisPreparationJournal } from "./artemis-preparation-journal.js";
import { PreparationActionBroker,PreparationBrokerError,type PhysicalPreparationInspector,type PhysicalPreparationScope } from "./preparation-action-broker.js";
import { createAdmissionRecord } from "./network-admission-core.js";
import { canonicalMaterial } from "./material-registry-core.js";
const url=process.env.SG_PRODUCT_TEST_DATABASE_URL,cluster=process.env.SG_PRODUCT_TEST_CLUSTER_ID;
if(!url||!cluster||process.env.SG_PRODUCT_TEST_ALLOW_RESET!=="1"||new URL(url).hostname!=="127.0.0.1"||new URL(url).pathname!=="/sg_broker6_component")throw new Error("Owned isolated broker component DB required");
const pool=new Pool({connectionString:url,max:12}),s="socialgrowth_product",pepper="synthetic-broker-component-pepper-0001";
const auth=new InstallationAuthService(pool,pepper),local=new LocalParticipationService(pool,auth),journal=new PhoneControlJournal(pool);
const preparations=new AccountPreparationService(pool,new OperatorAuthService(pool,pepper));
const launchJournal=new PostgresArtemisPreparationJournal(pool);
const hash=(v:unknown)=>createHash("sha256").update(canonicalMaterial(v)).digest("hex");
const meta=()=>({contractVersion,requestId:`request-${randomUUID()}`,idempotencyKey:`request-${randomUUID()}`});
async function guard(){const r=(await pool.query("select current_database() db,system_identifier::text cluster from pg_control_system()")).rows[0];assert.equal(r.db,"sg_broker6_component");assert.equal(r.cluster,cluster);}
before(async()=>{await guard();await pool.query(`DROP SCHEMA IF EXISTS ${s} CASCADE`);const dir=new URL("../migrations/",import.meta.url);for(const f of (await readdir(dir)).filter(f=>/^\d{4}.*\.sql$/.test(f)).sort())await pool.query(await readFile(new URL(f,dir),"utf8"));});
after(async()=>{try{await guard();await pool.query(`DROP SCHEMA IF EXISTS ${s} CASCADE`);}finally{await pool.end();}});
async function clock(){return(await pool.query<{now:Date}>("select clock_timestamp() now")).rows[0]!.now.toISOString();}
// Synthetic central identities, network evidence and stop proofs ONLY. Real SQL
// transactions are exercised; no device/ADB/Artemis or Web success is simulated.
async function fixture(){
const actor=randomUUID(),provider=randomUUID(),projectId=randomUUID(),deviceId=randomUUID(),accountId=randomUUID(),association=randomUUID(),assocSession=randomUUID();
const token=randomBytes(32).toString("base64url"),csrf=randomBytes(32).toString("base64url"),sha=(v:string)=>createHash("sha256").update(v).digest();
await pool.query(`INSERT INTO ${s}.operators(operator_id,login_name,display_name,password_hash,status) VALUES($1,$2,'Synthetic broker author','not-a-password','active')`,[actor,`fixture-${actor}`]);
await pool.query(`INSERT INTO ${s}.operator_sessions(session_id,operator_id,token_digest,csrf_digest,credential_version,expires_at) VALUES($1,$2,$3,$4,1,clock_timestamp()+interval '1 day')`,[randomUUID(),actor,sha(token),sha(csrf)]);
await pool.query(`INSERT INTO ${s}.projects(project_id,name,kind,created_by_operator_id) VALUES($1,'Synthetic broker project','company_owned',$2)`,[projectId,actor]);
const identity=await auth.bootstrap({metadata:meta(),installationCredential:`sginst_v1_${randomBytes(32).toString("base64url")}`},`source-${randomUUID()}`);
await pool.query(`INSERT INTO ${s}.providers(provider_id,phone_e164,display_name,status) VALUES($1,$2,'Synthetic broker owner','active')`,[provider,`+86${Math.floor(1e10+Math.random()*8e10)}`]);
await pool.query(`INSERT INTO ${s}.devices(device_id,display_name,state) VALUES($1,'Synthetic broker device','associated_pending_access')`,[deviceId]);
await pool.query(`INSERT INTO ${s}.association_sessions(association_session_id,installation_id,expected_installation_generation,device_label,code_digest,expires_at) VALUES($1,$2,1,'Synthetic association',$3,clock_timestamp()+interval '1 hour')`,[assocSession,identity.installation.installationId,randomBytes(32)]);
await pool.query(`INSERT INTO ${s}.device_associations(association_id,device_id,installation_id,provider_id,association_session_id) VALUES($1,$2,$3,$4,$5)`,[association,deviceId,identity.installation.installationId,provider,assocSession]);
const parent=`parent_${randomUUID().replaceAll("-","")}`;await pool.query(`INSERT INTO ${s}.media_accounts(account_id,platform,canonical_account_ref) VALUES($1,'facebook',$2)`,[accountId,parent]);
await pool.query(`INSERT INTO ${s}.project_account_reservations(account_id,project_id) VALUES($1,$2)`,[accountId,projectId]);await pool.query(`INSERT INTO ${s}.project_device_reservations(device_id,project_id) VALUES($1,$2)`,[deviceId,projectId]);
await pool.query(`INSERT INTO ${s}.project_media_account_assignments(account_id,platform,project_id,device_id,reserved_by_operator_id) VALUES($1,'facebook',$2,$3,$4)`,[accountId,projectId,deviceId,actor]);
const intent={accountId,deviceId,parentLoginRef:null,mode:"check_only",target:{platform:"facebook",name:"Synthetic Page",expectedId:null,category:null,description:""},scopeRef:"synthetic-author-scope",allowTrustedInstall:false,allowIdentityCreation:false};
const workspace=await preparations.write(token,csrf,{metadata:meta(),protocolVersion:executionLibraryVersion,projectId,expectedProjectVersion:0,expectedResourceVersion:0,intent},"request");
const task=workspace.tasks[0]!,assignment=artemisPreparationAssignmentSchema.parse({taskId:task.taskId,taskVersion:0,taskAttemptId:randomUUID(),serial:`SYNTHETIC_${randomUUID().replaceAll("-","")}`,operationId:"inspect_app",input:{protocolVersion:executionLibraryVersion,projectId,accountId,deviceId,mode:intent.mode,target:intent.target,requestedScope:{scopeRef:intent.scopeRef,allowTrustedInstall:false,allowIdentityCreation:false},facts:{version:1,currentScopeMatches:true,unresolvedDeviceTask:false,boundIdentityId:null,priorCreation:"none",app:{state:"unknown",evidenceRef:null},login:{state:"unknown",evidenceRef:null},identity:{state:"unknown",observedId:null,observedName:null,kind:null,managementVerified:false,evidenceRef:null}}}});
const fingerprint=createHash("sha256").update(JSON.stringify(assignment)).digest("hex");await launchJournal.claim(assignment,fingerprint);
const stop=randomUUID(),initial=await journal.initialize(deviceId,stop,`initialize-${randomUUID()}`);
await journal.apply(deviceId,initial.record.version,`stopped-${randomUUID()}`,{kind:"confirm_stopped",evidence:{deviceId,holderId:null,stopRequestId:stop,controlGeneration:"1",evidenceId:randomUUID(),checkedAt:await clock(),allPathsFenced:true,controllerReleased:true,targetQuiescent:true}});
const runId=randomUUID(),body=()=>({protocolVersion:participationProtocolVersion,runId,requestId:randomUUID(),requestKey:randomUUID()});await local.start(identity.sessionToken,body());const nonce=await local.challenge(identity.sessionToken,body());await local.confirm(identity.sessionToken,{...body(),challengeId:nonce.challengeId});
const spki=generateKeyPairSync("ec",{namedCurve:"prime256v1"}).publicKey.export({type:"spki",format:"der"}).toString("base64url");const record=createAdmissionRecord({deviceId,installationId:identity.installation.installationId,installationGeneration:"1",enrollmentGeneration:"1",ownershipVersion:"0",eligible:true},spki,await clock());
const node={nodeId:`node_${randomUUID()}`,nodeKey:`synthetic_node_${randomUUID()}`,networkRevision:1};
const admitted={...record,phase:"admitted",version:5,node,proofDigest:"a".repeat(64),formalPolicyRevision:2,formalEvidenceId:randomUUID(),restriction:{enrollmentId:record.enrollmentId,deviceId,installationId:identity.installation.installationId,enrollmentGeneration:"1",evidenceId:randomUUID(),policyRevision:1,networkRevision:1,checkedAt:await clock(),independentVerifierReachable:true,adbDenied:true,otherPhonesDenied:true,operatorServicesDenied:true,businessEgressDenied:true,additiveRulesChecked:true}};
await pool.query(`INSERT INTO ${s}.network_enrollments(enrollment_id,installation_id,device_id,association_id,provider_id,generation,request_key,key_digest,version,phase,candidate_node_id,record,created_at,expires_at) VALUES($1,$2,$3,$4,$5,1,$6,$7,5,'admitted',$8,$9,$10,$11)`,[record.enrollmentId,identity.installation.installationId,deviceId,association,provider,randomUUID(),randomBytes(32),node.nodeId,admitted,record.createdAt,record.expiresAt]);
const request:PhoneActionRequest={protocolVersion:controlProtocolVersion,deviceId,holderId:randomUUID(),controlGeneration:"1",authorizationId:task.taskId,taskAttemptId:assignment.taskAttemptId,actionId:randomUUID(),purpose:"business",kind:"read_screen"};
const {actionId:_a,kind:_k,...holder}=request;
return{request,holder,actor,provider,deviceId,projectId,accountId,association,assignment,fingerprint,installationId:identity.installation.installationId,sessionId:identity.session.sessionId,networkId:record.enrollmentId,token:identity.sessionToken,runId,body};}
type Fixture=Awaited<ReturnType<typeof fixture>>;
function observation(scope:Readonly<PhysicalPreparationScope>,nonce:string){const now=new Date();return{nonce,scopeDigest:hash(scope),checkedAt:now.toISOString(),validUntil:new Date(now.getTime()+2000).toISOString(),networkAdmitted:true,adbAuthorized:true,targetVerified:true,allPathsFenced:true,targetQuiescent:true,sensitiveObservationBlocked:false,targetFieldVerified:false,loginSubmitTargetVerified:false,controllerOwnership:scope.controlDisposition==="stopped"?"released":"held"};}
const inspector:PhysicalPreparationInspector={async inspect(scope,nonce){return observation(scope,nonce);}};
const isAuthority=(e:unknown)=>e instanceof PreparationBrokerError&&e.code==="CURRENT_AUTHORITY_REQUIRED";
async function counts(f:Fixture){return(await pool.query(`SELECT (SELECT count(*)::int FROM ${s}.phone_control_holder_grants WHERE device_id=$1) grants,(SELECT count(*)::int FROM ${s}.phone_control_commands WHERE device_id=$1 AND kind='begin_call') calls,(SELECT count(*)::int FROM ${s}.audit_records WHERE object_id=$1 AND action LIKE 'preparation.broker.%') audits`,[f.deviceId])).rows[0];}
test("real central scope grants one bounded read holder and atomically records original action before its short ticket",async()=>{const f=await fixture(),broker=new PreparationActionBroker(pool,inspector);const grant=await broker.acquireHolder(f.holder);assert.equal(grant.journal.replayed,false);assert.equal(grant.ticket,null);const until=(await pool.query(`select record->>'leaseUntil' until from ${s}.phone_control_holder_grants where holder_id=$1`,[f.request.holderId])).rows[0].until;assert.ok(Date.parse(until)-Date.now()<=30000);
const start=await broker.beginAction(f.request);assert.ok(start.ticket);assert.equal(start.ticket.serial,f.assignment.serial);assert.equal(start.ticket.replayed,false);assert.ok(Date.parse(start.ticket.validUntil)-Date.parse(start.ticket.checkedAt)<=2000);assert.equal(start.journal.record.calls[0]!.status,"running");assert.deepEqual(await counts(f),{grants:1,calls:1,audits:2});});
test("handover-requested R159 account-device pair denies access despite both project reservations",async()=>{const f=await fixture();await pool.query(`UPDATE ${s}.project_media_account_assignments SET handover_requested=true WHERE account_id=$1 AND platform='facebook' AND project_id=$2 AND device_id=$3`,[f.accountId,f.projectId,f.deviceId]);await assert.rejects(new PreparationActionBroker(pool,inspector).acquireHolder(f.holder),isAuthority);assert.deepEqual(await counts(f),{grants:0,calls:0,audits:0});});
test("absent real inspector and missing or stale network refuse grant rather than using admitted or USB flags",async()=>{const f=await fixture();await assert.rejects(new PreparationActionBroker(pool).acquireHolder(f.holder),(e:unknown)=>e instanceof PreparationBrokerError&&e.code==="PHYSICAL_BOUNDARY_REQUIRED");assert.deepEqual(await counts(f),{grants:0,calls:0,audits:0});await pool.query(`UPDATE ${s}.network_enrollments SET record=jsonb_set(record,'{authority,ownershipVersion}','"1"') WHERE enrollment_id=$1`,[f.networkId]);await assert.rejects(new PreparationActionBroker(pool,inspector).acquireHolder(f.holder),isAuthority);});
test("nonce, target, stopped ownership, future time, expired proof and missing path fence all deny atomically",async()=>{for(const variant of ["nonce","scope","owner","future","expired","fence"]){const f=await fixture();const bad:PhysicalPreparationInspector={async inspect(scope,nonce){const r=observation(scope,nonce);if(variant==="nonce")r.nonce=randomUUID();if(variant==="scope")r.scopeDigest="b".repeat(64);if(variant==="owner")r.controllerOwnership="held";if(variant==="fence")r.allPathsFenced=false;if(["future","expired"].includes(variant)){const time=Date.now()+(variant==="future"?10000:-3000);r.checkedAt=new Date(time).toISOString();r.validUntil=new Date(time+2000).toISOString();}return r;}};await assert.rejects(new PreparationActionBroker(pool,bad).acquireHolder(f.holder));assert.equal((await counts(f)).grants,0);}});
test("pause, role disable, allocation loss, task version and installation replacement during external wait cannot become a grant",async()=>{for(const kind of ["pause","owner","operator","allocation","task","installation","participation","network"]){const f=await fixture();const changing:PhysicalPreparationInspector={async inspect(scope,nonce){
if(kind==="participation")await local.withdraw(f.token,f.body());
if(kind==="network")await pool.query(`UPDATE ${s}.network_enrollments SET phase='reclaim_pending',record=record||jsonb_build_object('phase','reclaim_pending','reclaimReason','fixture','reclamationId',$2::text) WHERE enrollment_id=$1`,[f.networkId,randomUUID()]);
if(kind==="pause")await pool.query(`UPDATE ${s}.devices SET state='paused' WHERE device_id=$1`,[f.deviceId]);
if(kind==="owner")await pool.query(`UPDATE ${s}.providers SET status='disabled' WHERE provider_id=$1`,[f.provider]);
if(kind==="operator")await pool.query(`UPDATE ${s}.operators SET status='disabled',disabled_at=clock_timestamp() WHERE operator_id=$1`,[f.actor]);
if(kind==="allocation")await pool.query(`DELETE FROM ${s}.project_device_reservations WHERE device_id=$1`,[f.deviceId]);
if(kind==="task")await pool.query(`UPDATE ${s}.account_preparation_tasks SET task_version=1 WHERE task_id=$1`,[f.assignment.taskId]);
if(kind==="installation")await pool.query(`UPDATE ${s}.installations SET status='replaced',generation=2 WHERE installation_id=$1`,[f.installationId]);
return observation(scope,nonce);}};await assert.rejects(new PreparationActionBroker(pool,changing).acquireHolder(f.holder));assert.equal((await counts(f)).grants,0);}});
test("external observation owns no SQL device or metadata lock; another phone proceeds while first probe waits",async()=>{const first=await fixture(),second=await fixture();let release!:()=>void,entered!:()=>void;const enteredPromise=new Promise<void>(r=>entered=r),gate=new Promise<void>(r=>release=r);
const waiting:PhysicalPreparationInspector={async inspect(scope,nonce){const c=await pool.connect();try{await c.query("BEGIN");await c.query("SET LOCAL lock_timeout='500ms'");await c.query(`SELECT 1 FROM ${s}.resource_reservation_guard FOR UPDATE`);await c.query(`SELECT 1 FROM ${s}.devices WHERE device_id=$1 FOR UPDATE`,[scope.deviceId]);await c.query("ROLLBACK");}finally{c.release();}entered();await gate;return observation(scope,nonce);}};
const pending=new PreparationActionBroker(pool,waiting).acquireHolder(first.holder);await enteredPromise;try{assert.equal((await new PreparationActionBroker(pool,inspector).acquireHolder(second.holder)).journal.replayed,false);}finally{release();}await pending;});
test("same-holder races return one new grant and one acknowledgement; distinct actions cannot both obtain tickets",async()=>{const f=await fixture(),broker=new PreparationActionBroker(pool,inspector);const grants=await Promise.all([broker.acquireHolder(f.holder),broker.acquireHolder(f.holder)]);assert.equal(grants.filter(g=>!g.journal.replayed).length,1);assert.equal(grants.filter(g=>g.journal.replayed).length,1);
const results=await Promise.allSettled([broker.beginAction(f.request),broker.beginAction({...f.request,actionId:randomUUID()})]);assert.equal(results.filter(r=>r.status==="fulfilled").length,1);assert.equal((await counts(f)).calls,1);});
test("lost grant/call ACK and a later pause replay history only, with no additional inspector call or ticket",async()=>{const f=await fixture();let probes=0;const broker=new PreparationActionBroker(pool,{async inspect(scope,nonce){probes++;return observation(scope,nonce);}});await broker.acquireHolder(f.holder);assert.equal((await broker.acquireHolder(f.holder)).journal.replayed,true);await broker.beginAction(f.request);const before=await counts(f);await journal.apply(f.deviceId,(await journal.read(f.deviceId)).version,`stop-${randomUUID()}`,{kind:"request_stop",stopRequestId:randomUUID()});const replay=await broker.beginAction(f.request);assert.equal(replay.journal.replayed,true);assert.equal(replay.ticket,null);assert.equal(replay.journal.record.disposition,"stop_requested");assert.equal(probes,2);assert.deepEqual(await counts(f),before);});
test("broker evidence audit failure rolls back central original call and action permission together",async()=>{const f=await fixture(),broker=new PreparationActionBroker(pool,inspector);await broker.acquireHolder(f.holder);const before=await journal.read(f.deviceId),totals=await counts(f);await pool.query(`CREATE FUNCTION ${s}.deny_broker_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='preparation.broker.begin' THEN RAISE EXCEPTION 'fixture-private'; END IF; RETURN NEW; END $$; CREATE TRIGGER deny_broker_audit BEFORE INSERT ON ${s}.audit_records FOR EACH ROW EXECUTE FUNCTION ${s}.deny_broker_audit()`);
try{await assert.rejects(broker.beginAction(f.request));assert.deepEqual(await journal.read(f.deviceId),before);assert.deepEqual(await counts(f),totals);}finally{await pool.query(`DROP TRIGGER deny_broker_audit ON ${s}.audit_records;DROP FUNCTION ${s}.deny_broker_audit()`);}});
test("terminal or unknown original observation, forged task authority and non-read scope cannot obtain any new action",async()=>{const f=await fixture(),broker=new PreparationActionBroker(pool,inspector);await assert.rejects(broker.acquireHolder({...f.holder,authorizationId:randomUUID()}));await broker.acquireHolder(f.holder);for(const kind of ["navigate","write_input","submit_publication","remove_content","sign_out"])await assert.rejects(broker.beginAction({...f.request,kind}),isAuthority);
await launchJournal.record(f.assignment.taskAttemptId,f.fingerprint,{traceId:null,state:"launch_unknown",evidenceIds:[],identityVerified:false,publicationAllowed:false});await assert.rejects(broker.beginAction(f.request),isAuthority);assert.equal((await counts(f)).calls,0);});

test("proof expiry while final audit waits rolls back the holder rather than committing a stale permission",async()=>{
const f=await fixture(),broker=new PreparationActionBroker(pool,inspector),before=await journal.read(f.deviceId);
await pool.query(`CREATE FUNCTION ${s}.delay_broker_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.action='preparation.broker.acquire' THEN PERFORM pg_sleep(2.1); END IF; RETURN NEW; END $$;CREATE TRIGGER delay_broker_audit BEFORE INSERT ON ${s}.audit_records FOR EACH ROW EXECUTE FUNCTION ${s}.delay_broker_audit()`);
try{await assert.rejects(broker.acquireHolder(f.holder),(e:unknown)=>e instanceof PreparationBrokerError&&e.code==='PHYSICAL_BOUNDARY_REQUIRED');assert.deepEqual(await journal.read(f.deviceId),before);assert.deepEqual(await counts(f),{grants:0,calls:0,audits:0});}finally{await pool.query(`DROP TRIGGER delay_broker_audit ON ${s}.audit_records;DROP FUNCTION ${s}.delay_broker_audit()`);}
});
test("action ticket never outlives the current installation session",async()=>{const f=await fixture(),broker=new PreparationActionBroker(pool,inspector);await broker.acquireHolder(f.holder);const expires=(await pool.query<{expires_at:Date}>(`UPDATE ${s}.installation_sessions SET expires_at=clock_timestamp()+interval '900 milliseconds' WHERE session_id=$1 RETURNING expires_at`,[f.sessionId])).rows[0]!.expires_at;const result=await broker.beginAction(f.request);assert.ok(result.ticket);assert.equal(result.ticket.validUntil,expires.toISOString());});

test("timed-out external inspection is aborted and cannot commit a later acknowledgement",async()=>{const f=await fixture();let aborted=false;const broker=new PreparationActionBroker(pool,{inspect(_scope,_nonce,signal){return new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>{aborted=true;reject(new Error('fixture-private-timeout'));},{once:true}));}});await assert.rejects(broker.acquireHolder(f.holder),(e:unknown)=>e instanceof PreparationBrokerError&&e.code==='PHYSICAL_BOUNDARY_REQUIRED');assert.equal(aborted,true);assert.deepEqual(await counts(f),{grants:0,calls:0,audits:0});});
