import { chromium, type Page } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

// Tests only the fictional, disconnected design artifact through its visible UI.
// This is NOT production Web acceptance or evidence of real device operations.
const output = new URL('./checks/', import.meta.url);
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const checks: string[] = [];
const errors: string[] = [];
const network: string[] = [];
const command = 'pnpm exec tsx docs/design/workbench/prototype/verify-prototype.mts';
let page: Page | undefined;
try {
  const context = await browser.newContext({ viewport: { width: 1500, height: 1080 } });
  await context.route(/^https?:/, route => { network.push(route.request().url()); return route.abort(); });
  page = await context.newPage();
  const ui = page;
  ui.on('pageerror', error => errors.push(error.message));
  ui.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  ui.on('dialog', dialog => dialog.accept());
  const click = (name: string) => ui.getByRole('button', { name, exact: true }).click();
  const visible = async (text: string) => assert.equal(await ui.getByText(text, { exact: true }).first().isVisible(), true, text);
  const heading = async (text: string) => assert.equal(await ui.getByRole('heading', { name: text, exact: true, level: 1 }).isVisible(), true);
  const demo = async (name: string) => { if (await ui.locator('details').getAttribute('open') === null) await ui.locator('details summary').click(); await click(name); };
  const shot = (name: string) => ui.screenshot({ path: fileURLToPath(new URL(name, output)), fullPage: true });
  const nav = (name: string) => ui.getByRole('navigation').getByRole('button', { name, exact: true }).click();
  await ui.goto(new URL('./index.html', import.meta.url).href);
  await heading('工作台');
  await shot('home.png');
  await ui.locator('#inbox-filter').selectOption('mine');
  await ui.getByLabel('本次实际观察').fill('演示记录：身份需核对，尚未取得发布依据。');
  await click('查看关联任务');
  assert.equal(await ui.getByRole('dialog').isVisible(), true);
  await visible('有未保存修改');
  await click('继续编辑');
  await heading('工作台');
  assert.equal(await ui.getByRole('button', { name: '查看关联任务', exact: true }).evaluate(el => el === document.activeElement), true);
  await click('查看关联任务');
  await click('保留草稿并离开');
  await heading('海岸来信 · 第3集');
  await click('← 返回来源页面');
  assert.equal(await ui.locator('#inbox-filter').inputValue(), 'mine');
  assert.equal(await ui.locator('#notes').inputValue(), '演示记录：身份需核对，尚未取得发布依据。');
  await visible('有未保存修改');
  await ui.reload();
  assert.equal(await ui.locator('#notes').inputValue(), '演示记录：身份需核对，尚未取得发布依据。');
  await click('提交处理结果');
  await visible('结果待核实');
  checks.push('草稿继续编辑/保留离开/来源返回/筛选与刷新恢复；提交说明不核验发布');

  await click('查看关联任务');
  await click('查看设备协助');
  await click('申请接管');
  await visible('接管申请已受理 · 等待独占');
  assert.equal(await ui.getByRole('button', { name: '交还手机', exact: true }).isDisabled(), true);
  await demo('演示回传：AI停止并授予独占');
  await visible('演示独占控制：李运营（你）');
  await ui.getByLabel('记录实际观察（演示输入）').fill('演示观察：已核对当前频道，等待平台独立核验。');
  await click('提交处理结果');
  await visible('演示独占控制：李运营（你）');
  await visible('结果待核实');
  await shot('device-control.png');
  await click('交还手机');
  await visible('交还请求已受理 · 等待确认');
  await demo('演示回传：交还已确认');
  await visible('手机已交还 · 恢复复核中');
  await demo('演示回传：平台发布核验通过');
  await visible('发布已核验');
  await visible('待复核');
  await demo('演示回传：设备复核通过');
  await visible('复核通过；任务仍单独判断');
  await click('← 返回来源页面');
  await visible('发布已核验');
  await visible('待采集，不记零');
  await click('打开原核实待办');
  await visible('发布已核验');
  checks.push('申请/独占/提交说明/交还/平台核验/设备复核分别反馈，并同步原任务和原待办');

  await nav('项目');
  await click('进入准备清单');
  await click('整理素材');
  await ui.locator('#language').selectOption({ label: '西班牙语' });
  await click('保存当前素材资料');
  await visible('资料已保存，检查待回传');
  await demo('演示回传：资料检查通过');
  await click('返回准备清单');
  await visible('资料检查通过；按批准规则判定候选');
  await click('查看方向摘要');
  await click('确认方向');
  assert.equal(await ui.getByRole('button', { name: '确认方向', exact: true }).isDisabled(), true);
  await click('返回准备清单');
  await visible('YT初始化中');
  await visible('链接已保存，入口待核验');
  checks.push('素材保存与检查分开；方向一次确认仍保留初始化和入口阻断');

  await nav('项目');
  await click('进入运行项目');
  await click('设置');
  await ui.locator('#interval').selectOption('7');
  await nav('提供者与分佣');
  await click('保留草稿并离开');
  await click('查看收入与分佣依据');
  await ui.getByLabel('核对情况及仍缺条件').fill('这条佣金说明将放弃。');
  await nav('项目');
  await click('放弃修改并离开');
  await click('进入运行项目');
  await click('设置');
  assert.equal(await ui.locator('#interval').inputValue(), '7');
  await visible('有未保存修改');
  await ui.locator('#interval').selectOption('14');
  await click('保存，下周期生效');
  await visible('2026-09-27 00:00 → 2026-10-04 00:00');
  await visible('拟定起点：2026-10-03 23:00 +07:00；下一周期 14 天。');
  await visible('已保存待生效配置；从当前周期结束的同一实际时刻生效，尚未运行新配置。');
  checks.push('放弃只影响当前表单，其他页草稿保留；周期变更待生效，当前周期不变');

  await click('概览');
  await click('暂停项目发布');
  await click('返回，暂不暂停');
  assert.equal(await ui.getByRole('button', { name: '暂停项目发布', exact: true }).isEnabled(), true);
  await click('暂停项目发布');
  await click('确认暂停发布');
  await visible('暂停请求已受理；停止新增已生效，仍等待在途停止确认。');
  await demo('演示回传：在途停止已确认');
  await click('返回项目概览');
  await click('恢复并检查任务');
  await click('确认恢复并检查');
  await visible('恢复请求已受理，正在等待逐任务检查结果。');
  await demo('演示回传：恢复检查完成');
  await visible('窗口已过，继续受阻');
  await click('返回项目概览');
  await click('查看正式结束影响');
  await click('返回，保持当前状态');
  assert.equal(await ui.getByRole('button', { name: '暂停项目发布', exact: true }).isEnabled(), true);
  await click('查看正式结束影响');
  await click('确认结束项目');
  await demo('演示回传：停止和未提交取消已确认');
  assert.equal(await ui.getByText('已取消（演示）', { exact: true }).count(), 2);
  await shot('ended.png');
  await click('返回项目概览');
  assert.equal(await ui.getByRole('button', { name: '恢复并检查任务', exact: true }).isDisabled(), true);
  checks.push('暂停取消/受理/停止确认、恢复检查、结束返回/确认/收尾；已结束不可普通恢复');

  await nav('提供者与分佣');
  await click('查看收入与分佣依据');
  assert.equal(await ui.locator('#commissionNote').inputValue(), '');
  await ui.getByLabel('核对情况及仍缺条件').fill('演示：比例仍待配置，不代表已支付。');
  await click('保存处理记录');
  assert.equal(await ui.locator('.metric').nth(1).locator('strong').textContent(), '—');
  assert.equal(await ui.locator('.metric').nth(2).locator('strong').textContent(), '—');
  checks.push('收入、佣金、付款分开；保存说明不生成比例、金额或付款');

  await nav('工作台');
  await ui.locator('#inbox-filter').selectOption('none');
  await visible('选择其他查看范围以继续。');
  await ui.locator('#inbox-filter').selectOption('all');
  await ui.locator('#queue-device').click();
  await click('查看设备与协助');
  await heading('核对当前频道与页面');
  await click('← 返回来源页面');
  assert.equal(await ui.locator('#queue-device').getAttribute('aria-pressed'), 'true');
  await ui.locator('#queue-window').click();
  await click('查看关联安排');
  await heading('发布安排');
  checks.push('空筛选不冒充全部完成，设备/窗口待办分别关联正确对象');

  for (const width of [1500, 1100, 390]) {
    await ui.setViewportSize({ width, height: 1000 });
    await nav('工作台');
    await ui.locator('#queue-verify').click();
    assert.equal(await ui.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `viewport ${width}`);
    if (width === 390) {
      assert.equal(await ui.getByRole('button', { name: '提交处理结果', exact: true }).isDisabled(), true);
      assert.equal(await ui.locator('#notes').isDisabled(), true);
      await shot('mobile-read-only.png');
    }
  }
  await ui.setViewportSize({ width: 1500, height: 1080 });
  await ui.waitForFunction(() => !document.querySelector<HTMLButtonElement>('button[data-action="save-note"]')?.disabled);
  assert.equal(await ui.getByRole('button', { name: '提交处理结果', exact: true }).isEnabled(), true);
  checks.push('1500/1100/390宽度无页面横向溢出；手机仅查看；回到电脑可继续处理');

  await click('重置演示');
  await click('确认重置演示');
  await nav('项目');
  await click('进入运行项目');
  await click('查看正式结束影响');
  await click('确认结束项目');
  await demo('演示回传：停止和未提交取消已确认');
  await visible('结果待核实');
  await click('查看原核实任务');
  await visible('结果待核实');
  checks.push('未核实发布在项目结束后仍关联原任务，未被取消或重发');
  assert.deepEqual(errors, []);
  assert.deepEqual(network, []);
  await rm(new URL('failure.png', output), { force: true });
  await writeFile(new URL('result.json', output), JSON.stringify({ kind: 'clickable-design-prototype-check', status: 'passed', checkedAt: new Date().toISOString(), command, browser: browser.version(), checks, errors, externalRequests: network, runtimeConnected: false, deviceCommandsSent: false, businessAcceptance: 'not-run' }, null, 2) + '\n');
  console.log(JSON.stringify({ status: 'passed', scenarios: checks.length, checks, businessAcceptance: 'not-run' }, null, 2));
} catch (error) {
  await page?.screenshot({ path: fileURLToPath(new URL('failure.png', output)), fullPage: true });
  await writeFile(new URL('result.json', output), JSON.stringify({ status: 'failed', command, completedChecks: checks, error: String(error), errors, businessAcceptance: 'not-run' }, null, 2) + '\n');
  console.error(JSON.stringify({ context: 'design-prototype-check', error: error instanceof Error ? error.stack : String(error) }));
  process.exitCode = 1;
} finally {
  await browser.close();
}
