// Generated by product/contracts; do not edit manually.
package com.socialgrowth.product

internal object GeneratedFirstBatchContractSpec {
    const val CONTRACT_VERSION = "2026-09-29.identity-v1"
    const val ASSOCIATION_CODE_PATTERN = "^sgassoc_v1_[A-Za-z0-9_-]{43}\$"
    const val UUID_PATTERN = "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)\$"
    const val TIMESTAMP_PATTERN = "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))\$"
    const val FACT_VERSION_MAX = 9007199254740991L
    const val FACT_VERSION_MIN = 0L
    const val REQUEST_ID_MIN_LENGTH = 8
    const val REQUEST_ID_MAX_LENGTH = 128
    const val ERROR_MESSAGE_MIN_LENGTH = 1
    const val ERROR_FIELD_MIN_LENGTH = 1
    const val PHONE_HINT_PATTERN = "^\\+(?=[0-9*]{7,18}\$)(?=[0-9]*\\*)[0-9*]+\$"
    const val SESSION_TOKEN_PATTERN = "^[A-Za-z0-9_-]{43}\$"
    const val PHONE_CHALLENGE_DELIVERY_STATE = "accepted"
    const val PROVIDER_DISPLAY_NAME_MIN_CODE_POINTS = 1
    const val PROVIDER_DISPLAY_NAME_MAX_CODE_POINTS = 100
    val ASSOCIATION_QR_KEYS = setOf("contractVersion", "associationCode")
    val ASSOCIATION_QR_REQUIRED_KEYS = setOf("contractVersion", "associationCode")
    val INSTALLATION_SELF_KEYS = setOf("factVersion", "updatedAt", "installationId", "state", "deviceId")
    val INSTALLATION_SELF_REQUIRED_KEYS = setOf("factVersion", "updatedAt", "installationId", "state", "deviceId")
    val NULL_DEVICE_STATES = setOf("unassociated")
    val IDENTIFIED_DEVICE_STATES = setOf("associated_pending_access", "access_ready", "paused", "exit_pending", "exited")
    val ERROR_RESPONSE_KEYS = setOf("contractVersion", "requestId", "error")
    val ERROR_RESPONSE_REQUIRED_KEYS = setOf("contractVersion", "requestId", "error")
    val ERROR_DETAIL_KEYS = setOf("code", "message", "retryable", "field")
    val ERROR_DETAIL_REQUIRED_KEYS = setOf("code", "message", "retryable")
    val ERROR_CODES = setOf("AUTHENTICATION_REQUIRED", "AUTHORIZATION_DENIED", "INVALID_CREDENTIALS", "LOGIN_RATE_LIMITED", "OPERATOR_ALREADY_EXISTS", "OPERATOR_DISABLED", "LAST_ACTIVE_OPERATOR", "CONTRACT_VERSION_UNSUPPORTED", "IDEMPOTENCY_KEY_REUSED", "IDEMPOTENCY_RESULT_EXPIRED", "INSTALLATION_BOOTSTRAP_RATE_LIMITED", "INPUT_INVALID", "INTERNAL_ERROR", "INVITATION_EXPIRED", "INVITATION_EXHAUSTED", "INVITATION_REVOKED", "PHONE_ALREADY_REGISTERED", "PHONE_NOT_REGISTERED", "PHONE_VERIFICATION_CODE_INVALID", "PHONE_VERIFICATION_EXPIRED", "PHONE_VERIFICATION_INVALID", "PHONE_VERIFICATION_RATE_LIMITED", "PROVIDER_DISABLED", "SMS_DELIVERY_UNAVAILABLE", "ASSOCIATION_SESSION_EXPIRED", "ASSOCIATION_SESSION_CONSUMED", "ASSOCIATION_TARGET_CHANGED", "DEVICE_ALREADY_ASSOCIATED", "FACT_VERSION_STALE")
    val PHONE_VERIFICATION_PURPOSES = setOf("provider_registration", "provider_login")
    val PHONE_CHALLENGE_KEYS = setOf("challengeId", "purpose", "phoneHint", "deliveryState", "expiresAt", "resendAvailableAt")
    val PHONE_CHALLENGE_REQUIRED_KEYS = setOf("challengeId", "purpose", "phoneHint", "deliveryState", "expiresAt", "resendAvailableAt")
    val PHONE_PROOF_KEYS = setOf("phoneVerificationId", "purpose", "phoneHint", "verifiedAt", "expiresAt")
    val PHONE_PROOF_REQUIRED_KEYS = setOf("phoneVerificationId", "purpose", "phoneHint", "verifiedAt", "expiresAt")
    val PROVIDER_SELF_KEYS = setOf("providerId", "displayName", "phoneHint", "status", "createdAt", "updatedAt")
    val PROVIDER_SELF_REQUIRED_KEYS = setOf("providerId", "displayName", "phoneHint", "status", "createdAt", "updatedAt")
    val PROVIDER_STATUSES = setOf("active", "disabled")
    val PROVIDER_AUTH_KEYS = setOf("provider", "session", "sessionToken")
    val PROVIDER_AUTH_REQUIRED_KEYS = setOf("provider", "session", "sessionToken")
    val SESSION_KEYS = setOf("sessionId", "createdAt", "expiresAt")
    val SESSION_REQUIRED_KEYS = setOf("sessionId", "createdAt", "expiresAt")
}
