// Generated by product/contracts; do not edit manually.
package com.socialgrowth.product

internal object GeneratedFirstBatchContractSpec {
    const val CONTRACT_VERSION = "2026-09-29.identity-v1"
    const val ASSOCIATION_CODE_PATTERN = "^sgassoc_v1_[A-Za-z0-9_-]{43}\$"
    const val UUID_PATTERN = "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)\$"
    const val TIMESTAMP_PATTERN = "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))\$"
    const val FACT_VERSION_MAX = 9007199254740991L
    val ASSOCIATION_QR_KEYS = setOf("contractVersion", "associationCode")
    val INSTALLATION_SELF_KEYS = setOf("factVersion", "updatedAt", "installationId", "state", "deviceId")
    val INSTALLATION_STATES = setOf("unassociated", "associated_pending_access", "access_ready", "paused", "exit_pending", "exited")
    val ERROR_RESPONSE_KEYS = setOf("contractVersion", "requestId", "error")
    val ERROR_DETAIL_KEYS = setOf("code", "message", "retryable")
    val ERROR_CODES = setOf("AUTHENTICATION_REQUIRED", "AUTHORIZATION_DENIED", "CONTRACT_VERSION_UNSUPPORTED", "IDEMPOTENCY_KEY_REUSED", "IDEMPOTENCY_RESULT_EXPIRED", "INPUT_INVALID", "INVITATION_EXPIRED", "INVITATION_EXHAUSTED", "INVITATION_REVOKED", "PHONE_ALREADY_REGISTERED", "PHONE_VERIFICATION_INVALID", "ASSOCIATION_SESSION_EXPIRED", "ASSOCIATION_SESSION_CONSUMED", "ASSOCIATION_TARGET_CHANGED", "DEVICE_ALREADY_ASSOCIATED", "FACT_VERSION_STALE")
}
