// Generated by product/contracts; do not edit manually.
package com.socialgrowth.product

internal object GeneratedAdmissionApiSpec {
    val SNAPSHOT_KEYS = setOf("protocolVersion", "scope", "enrollment", "verifierReady", "networkAdmissionGranted", "actionPermissionGranted")
    val CHALLENGE_RESPONSE_KEYS = setOf("protocolVersion", "scope", "enrollment", "verifierReady", "networkAdmissionGranted", "actionPermissionGranted", "challenge")
    val SCOPE_KEYS = setOf("deviceId", "installationId", "installationGeneration", "ownershipVersion")
    val ENROLLMENT_KEYS = setOf("enrollmentId", "enrollmentGeneration", "version", "phase", "expiresAt")
    val PHASES = setOf("awaiting_restriction", "restricted", "proof_verified", "permission_pending", "admitted", "reclaim_pending", "reclaimed")
    val ERROR_KEYS = setOf("protocolVersion", "requestId", "error")
    val ERROR_DETAIL_KEYS = setOf("code", "retryable")
    val ERROR_CODES = setOf("INPUT_INVALID", "PROTOCOL_UNSUPPORTED", "AUTHENTICATION_REQUIRED", "AUTHORITY_CHANGED", "STALE_FACT", "EXPIRED", "INVALID_PHASE", "INVALID_EVIDENCE", "INVALID_PROOF", "SOURCE_MISMATCH", "VERIFIER_UNAVAILABLE", "INTERNAL_ERROR")
}
