// Generated by product/contracts; do not edit manually.
package com.socialgrowth.product

internal object GeneratedAdmissionContractSpec {
    const val PROTOCOL_VERSION = "2026-09-30.admission-v1"
    const val PURPOSE = "network_node_binding"
    const val UUID_PATTERN = "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)\$"
    const val TIMESTAMP_PATTERN = "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:\\.\\d+)?(?:Z|([+-](?:[01]\\d|2[0-3]):[0-5]\\d)))\$"
    const val GENERATION_PATTERN = "^[1-9][0-9]{0,18}\$"
    const val NONCE_PATTERN = "^[A-Za-z0-9_-]{43}\$"
    const val NODE_ID_PATTERN = "^[A-Za-z0-9_-]{1,128}\$"
    const val NODE_KEY_MIN = 1
    const val NODE_KEY_MAX = 256
    const val NETWORK_REVISION_MIN = 1L
    const val NETWORK_REVISION_MAX = 9007199254740991L
    val CHALLENGE_KEYS = setOf("protocolVersion", "purpose", "challengeId", "enrollmentId", "deviceId", "installationId", "installationGeneration", "enrollmentGeneration", "node", "nonce", "issuedAt", "expiresAt")
    val CHALLENGE_REQUIRED_KEYS = setOf("protocolVersion", "purpose", "challengeId", "enrollmentId", "deviceId", "installationId", "installationGeneration", "enrollmentGeneration", "node", "nonce", "issuedAt", "expiresAt")
    val NODE_KEYS = setOf("nodeId", "nodeKey", "networkRevision")
    val NODE_REQUIRED_KEYS = setOf("nodeId", "nodeKey", "networkRevision")
}
