import {build} from 'esbuild';
import {readFile,writeFile,readdir,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import React from 'react';
import {renderToString} from 'react-dom/server';
const root=process.cwd();
const cache=path.join(root,'node_modules/.cache/report-export');
await mkdir(cache,{recursive:true});
const common={bundle:true,alias:{'@':root},jsx:'automatic',logLevel:'warning',define:{'process.env.NODE_ENV':'"production"'}};
await build({...common,entryPoints:['app/page.tsx'],platform:'node',format:'esm',banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"},external:['react','react-dom','react/jsx-runtime'],outfile:path.join(cache,'page.mjs')});
const {default:Page}=await import(pathToFileURL(path.join(cache,'page.mjs')).href);
const markup=renderToString(React.createElement(Page));
const browser=await build({...common,stdin:{contents:"import React from 'react';import {hydrateRoot} from 'react-dom/client';import Page from './app/page';hydrateRoot(document.getElementById('root'),React.createElement(Page));",resolveDir:root,loader:'tsx'},platform:'browser',format:'iife',minify:true,write:false});
const cssDir=path.join(root,'dist/client/_next/static/css');
const cssFiles=(await readdir(cssDir)).filter(f=>f.endsWith('.css'));
if(!cssFiles.length)throw new Error('Build CSS is missing');
const css=(await Promise.all(cssFiles.map(f=>readFile(path.join(cssDir,f),'utf8')))).join('\n');
const js=browser.outputFiles[0].text.replace(/<\/script/gi,'<\\/script');
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>账号成长与创作者收益 · 商务研究报告</title><style>${css}</style></head><body><div id="root">${markup}</div><script>${js}</script></body></html>`;
await writeFile(path.join(root,'public/creator-revenue-report.html'),html);
const artifacts=path.resolve(root,'../../artifacts/reports');
await mkdir(artifacts,{recursive:true});
await writeFile(path.join(artifacts,'创作者收益与电商佣金-独立复核.html'),html);
await writeFile(path.join(artifacts,'账号成长与创作者收益-FacebookReels专项.html'),html);
await writeFile(path.join(artifacts,'账号成长与创作者收益-商务汇报.html'),html);
if(!markup.includes('资料来源与适用范围')||!markup.includes('Facebook Reels：准入门槛与平台收益'))throw new Error('Missing report sections');
if(/<script[^>]+src=|<link[^>]+stylesheet/i.test(html))throw new Error('Unexpected external runtime dependency');
console.log(`Standalone HTML exported: ${Buffer.byteLength(html)} bytes; SSR content, inline CSS and interaction bundle included.`);
