import { readFile, writeFile } from "node:fs/promises";
import { admissionSnapshotSchema, admissionChallengeResponseSchema, admissionErrorResponseSchema } from "./network-admission.js";

const output = new URL("../../android/app/src/main/java/com/socialgrowth/product/GeneratedAdmissionApiSpec.kt", import.meta.url);
const set = (values: string[]) => `setOf(${values.map(value => JSON.stringify(value).replaceAll("$", "\\$")).join(", ")})`;
const content = `// Generated by product/contracts; do not edit manually.
package com.socialgrowth.product

internal object GeneratedAdmissionApiSpec {
    val SNAPSHOT_KEYS = ${set(Object.keys(admissionSnapshotSchema.shape))}
    val CHALLENGE_RESPONSE_KEYS = ${set(Object.keys(admissionChallengeResponseSchema.shape))}
    val SCOPE_KEYS = ${set(Object.keys(admissionSnapshotSchema.shape.scope.shape))}
    val ENROLLMENT_KEYS = ${set(Object.keys(admissionSnapshotSchema.shape.enrollment.unwrap().shape))}
    val PHASES = ${set(admissionSnapshotSchema.shape.enrollment.unwrap().shape.phase.options)}
    val ERROR_KEYS = ${set(Object.keys(admissionErrorResponseSchema.shape))}
    val ERROR_DETAIL_KEYS = ${set(Object.keys(admissionErrorResponseSchema.shape.error.shape))}
    val ERROR_CODES = ${set(admissionErrorResponseSchema.shape.error.shape.code.options)}
}
`;
if (process.argv.includes("--check")) {
  if (await readFile(output, "utf8") !== content) throw new Error("Admission API generated boundary drifted");
} else await writeFile(output, content, "utf8");
