import { mkdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { z } from "zod";

import { contractVersion } from "./common.js";
import { firstBatchContractRegistry } from "./registry.js";

const outputUrl = new URL(
  "../generated/first-batch-contracts.v1.json",
  import.meta.url,
);
const androidOutputUrl = new URL(
  "../../android/app/src/main/java/com/socialgrowth/product/GeneratedFirstBatchContractSpec.kt",
  import.meta.url,
);

const schemas = Object.fromEntries(
  Object.entries(firstBatchContractRegistry).map(([name, schema]) => [
    name,
    z.toJSONSchema(schema, { target: "draft-2020-12" }),
  ]),
);

const generatedContent = `${JSON.stringify({ contractVersion, schemas }, null, 2)}\n`;

function kotlinString(value: string): string {
  return JSON.stringify(value).replaceAll("$", "\\$");
}

function kotlinSet(values: string[]): string {
  return `setOf(${values.map(kotlinString).join(", ")})`;
}

const associationQrSchema = schemas.associationQrPayload as unknown as {
  properties: Record<string, { pattern?: string }>;
  required: string[];
};
const installationSelfSchema = schemas.installationSelfView as unknown as {
  oneOf: Array<{
    properties: Record<
      string,
      {
        const?: string;
        enum?: string[];
        maximum?: number;
        pattern?: string;
      }
    >;
    required: string[];
  }>;
};
const productErrorSchema = schemas.productErrorResponse as unknown as {
  properties: {
    error: {
      properties: { code: { enum: string[] } };
      required: string[];
    };
  };
  required: string[];
};
const installationStates = installationSelfSchema.oneOf.flatMap((branch) => {
  const state = branch.properties.state;
  return state.enum ?? (state.const === undefined ? [] : [state.const]);
});
const installationProperties = installationSelfSchema.oneOf[0]?.properties;
const androidGeneratedContent = `// Generated by product/contracts; do not edit manually.
package com.socialgrowth.product

internal object GeneratedFirstBatchContractSpec {
    const val CONTRACT_VERSION = ${kotlinString(contractVersion)}
    const val ASSOCIATION_CODE_PATTERN = ${kotlinString(associationQrSchema.properties.associationCode?.pattern ?? "")}
    const val UUID_PATTERN = ${kotlinString(installationProperties?.installationId?.pattern ?? "")}
    const val TIMESTAMP_PATTERN = ${kotlinString(installationProperties?.updatedAt?.pattern ?? "")}
    const val FACT_VERSION_MAX = ${installationProperties?.factVersion?.maximum ?? 0}L
    val ASSOCIATION_QR_KEYS = ${kotlinSet(associationQrSchema.required)}
    val INSTALLATION_SELF_KEYS = ${kotlinSet(installationSelfSchema.oneOf[0]?.required ?? [])}
    val INSTALLATION_STATES = ${kotlinSet(installationStates)}
    val ERROR_RESPONSE_KEYS = ${kotlinSet(productErrorSchema.required)}
    val ERROR_DETAIL_KEYS = ${kotlinSet(productErrorSchema.properties.error.required)}
    val ERROR_CODES = ${kotlinSet(productErrorSchema.properties.error.properties.code.enum)}
}
`;

if (process.argv.includes("--check")) {
  const [committedContent, committedAndroidContent] = await Promise.all([
    readFile(outputUrl, "utf8"),
    readFile(androidOutputUrl, "utf8"),
  ]);
  if (
    committedContent !== generatedContent ||
    committedAndroidContent !== androidGeneratedContent
  ) {
    throw new Error(
      "Generated JSON/Kotlin contracts are stale. Run `pnpm --filter @socialgrowth/product-contracts generate` and commit the result.",
    );
  }
  process.exit(0);
}

await mkdir(fileURLToPath(new URL(".", outputUrl)), { recursive: true });
await mkdir(fileURLToPath(new URL(".", androidOutputUrl)), { recursive: true });
await Promise.all([
  writeFile(fileURLToPath(outputUrl), generatedContent, "utf8"),
  writeFile(fileURLToPath(androidOutputUrl), androidGeneratedContent, "utf8"),
]);
