import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {test} from "node:test";
import {participationProtocolVersion,participationChallengeSchema,participationReceiptSchema,participationRunRequestSchema} from "./local-participation.js";
const scope={deviceId:randomUUID(),associationId:randomUUID(),installationId:randomUUID(),installationGeneration:"9999999999999999999",deviceFactVersion:0,controlGeneration:"9007199254740993"};
const challenge={protocolVersion:participationProtocolVersion,challengeId:randomUUID(),runId:randomUUID(),sequence:"9007199254740993",scope,issuedAt:"2026-10-02T00:00:00.000Z",expiresAt:"2026-10-02T00:00:06.000Z"};
test("participation scope and sequence retain lossless digit generations",()=>assert.deepEqual(participationChallengeSchema.parse(challenge),challenge));
test("client request cannot submit scope, permission or claimed timestamps",()=>{const r={protocolVersion:participationProtocolVersion,requestId:randomUUID(),requestKey:randomUUID(),runId:randomUUID()};for(const extra of [{scope},{actionPermissionGranted:true},{checkedAt:challenge.issuedAt}])assert.equal(participationRunRequestSchema.safeParse({...r,...extra}).success,false);});
test("strict nonce and receipt TTL reject renewal, future-expiry extensions and stop proof",()=>{assert.equal(participationChallengeSchema.safeParse({...challenge,expiresAt:"2026-10-02T00:00:07.000Z"}).success,false);const r={protocolVersion:participationProtocolVersion,receiptId:randomUUID(),runId:challenge.runId,sequence:challenge.sequence,scope,state:"active",checkedAt:challenge.issuedAt,validUntil:"2026-10-02T00:00:10.000Z",actionPermissionGranted:false,stopConfirmed:false};assert.ok(participationReceiptSchema.safeParse(r).success);for(const extra of [{stopConfirmed:true},{actionPermissionGranted:true},{state:"withdrawn"},{validUntil:"2026-10-02T00:00:11.000Z"}])assert.equal(participationReceiptSchema.safeParse({...r,...extra}).success,false);assert.ok(participationReceiptSchema.safeParse({...r,state:"withdrawn",validUntil:r.checkedAt}).success);});
