import { chromium, type Locator } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { resolve, basename } from 'node:path';

// Real Web only. No API writes, database seeding, mocks, device task or publication.
const base = process.env.SOCIALGROWTH_WEB_URL ?? 'http://127.0.0.1:3000';
const output = resolve(process.env.SOCIALGROWTH_VERIFICATION_OUTPUT ?? 'artifacts/acceptance/operations-consolidation');
const files = process.argv.slice(2).map((f) => resolve(f));
if (!files.length) throw new Error('Provide 1-30 distinct synthetic MP4 fixture paths; never use a publishable customer clip here.');
await mkdir(output, { recursive: true });
const run = Date.now().toString();
const project = `Playwright运营验收-${run}`, account = `Playwright未绑定账号-${run}`;
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const results: string[] = [], errors: string[] = [];
page.on('pageerror', (e) => errors.push(e.message));
async function form(title: string) {
  const summary = page.getByText(title, { exact: true });
  await summary.waitFor();
  const box = summary.locator('..');
  if (await box.getAttribute('open') === null) await summary.click();
  return box;
}
async function submit(box: Locator, label: string) {
  await box.getByRole('button', { name: label, exact: true }).click();
  await box.getByText('已保存，列表和操作审计已更新。', { exact: true }).waitFor({ timeout: 30000 });
}
async function capture(name: string) { await page.screenshot({ path: resolve(output, `${name}.png`), fullPage: true }); }
try {
  await page.goto(`${base}/#/clients`);
  let box = await form('新建运营项目');
  await box.getByLabel('项目名称', { exact: true }).fill(project);
  await box.getByLabel('目标受众').fill('测试用途，不公开发布');
  await box.getByLabel('项目负责人').fill('Playwright验收');
  assert.equal(await box.getByLabel('客户', { exact: true }).count(), 0);
  await submit(box, '保存项目草稿');
  await page.getByRole('link', { name: `${project} · 自营`, exact: true }).click();
  const projectId = new URLSearchParams(page.url().split('?')[1]).get('project')!;
  assert.ok(projectId);
  await page.getByRole('button', { name: '资料已核对，激活项目', exact: true }).click();
  await page.getByRole('button', { name: '资料已核对，激活项目', exact: true }).waitFor({ state: 'detached' });
  results.push('自营项目无需客户输入，激活成功并保留 URL 项目上下文');
  box = await form('素材默认配置（批量导入继承）');
  await box.getByLabel('原始素材来源').fill('Playwright自生成测试卡');
  await box.getByLabel('内容权利依据').fill('本机自生成，仅测试，不发布');
  await submit(box, '保存项目默认值');
  await capture('01-project');
  await page.getByRole('link', { name: '账号接入与授权', exact: true }).click();
  box = await form('新增账号档案');
  await box.getByLabel('账号显示名称', { exact: true }).fill(account);
  await box.getByLabel('平台', { exact: true }).selectOption('facebook');
  await box.getByLabel('账号归属方').fill('Playwright验收');
  await box.getByLabel('内容定位').fill('仅本地表单验收，无真实设备绑定');
  await submit(box, '保存账号');
  await page.getByRole('link', { name: account, exact: true }).click();
  box = await form('新增项目授权');
  assert.equal(await box.getByLabel('运营项目', { exact: true }).inputValue(), projectId);
  await box.getByLabel('自有账号运营授权').selectOption('confirmed');
  await box.getByLabel('有效至').fill('2027-01-01T00:00');
  await submit(box, '保存授权');
  await page.getByText('授权有效', { exact: true }).waitFor();
  box = await form('接入 Page / 频道');
  await box.getByLabel('接入方式').selectOption('create');
  assert.equal(await box.getByLabel('Page 类别').count(), 1);
  // Merely inspect onboarding choices. Do not create a real identity as a UI fixture.
  await box.getByLabel('接入方式').selectOption('verify');
  results.push('自有账号结构化授权保存；已有身份核验 / 创建表单按接入方式切换，未发起平台创建');
  await capture('02-authorization');
  await page.goto(`${base}/#/content?project=${projectId}`);
  box = await form('批量导入切片');
  await box.getByLabel('剧集 / 导入批次').fill(`验收批次-${run}`);
  await box.getByLabel('切片文件').setInputFiles(files);
  await box.getByLabel('各文件故事范围').fill(files.map((_, i) => `第${i + 1}个自生成测试卡，独立测试画面，无客户剧情`).join('\n'));
  await box.getByLabel('内容身份核对').selectOption('yes');
  await submit(box, '上传并保存本批内容');
  for (const f of files) await page.getByRole('link', { name: basename(f, '.mp4'), exact: true }).waitFor();
  results.push(`真实浏览器选择并上传 ${files.length} 个 MP4，继承项目默认值，导入后待核对`);
  await capture('03-batch');
  await box.getByLabel('切片文件').setInputFiles(files);
  await box.getByRole('button', { name: '上传并保存本批内容', exact: true }).click();
  await box.getByRole('alert').filter({ hasText: '文件指纹重复' }).waitFor();
  results.push('重复批次被后端拒绝，未生成重复内容');
  const title = basename(files[0], '.mp4');
  await page.getByRole('link', { name: title, exact: true }).click();
  box = await form('更新适配核对');
  await box.getByLabel('适配结论').selectOption('eligible');
  await box.getByLabel('核对依据').fill('人工核对自生成测试卡，仅本地验收');
  await submit(box, '保存核对结论');
  box = await form('分配唯一目标账号');
  await box.locator('select').selectOption({ label: account });
  await box.getByRole('button', { name: '确认独占分配', exact: true }).click();
  await box.waitFor({ state: 'detached' });
  await page.getByText('独占分配', { exact: true }).waitFor();
  await page.getByRole('link', { name: '前往策略管理', exact: true }).click();
  box = await form('制定策略草案');
  await box.getByLabel('合格的独占内容').selectOption({ label: `${title} · ${account}` });
  assert.equal(await box.getByLabel('策略模板').inputValue(), 'daily_clip');
  assert.equal(await box.getByLabel('导流目的地').getAttribute('required'), null);
  await submit(box, '保存待审草案');
  await page.getByRole('link', { name: `${title} · v1`, exact: true }).click();
  await page.getByText('不使用导流目的地', { exact: true }).waitFor();
  assert.equal(await page.getByRole('link', { name: '查看来源 · v1', exact: true }).count(), 4);
  results.push('日常模板无需导流地址或手写策略依据，自动引用四条规则并保存真实草案');
  await capture('04-strategy');
  await page.goto(`${base}/#/rules?project=${projectId}`);
  box = await form('新增或修订规则');
  await box.getByLabel('规则模板').selectOption('custom');
  await box.getByLabel('依据类别').selectOption('internal_rule');
  await box.getByLabel('规则陈述').fill(`验收独立规则-${run}`);
  await box.getByLabel('来源 / 证据').fill('Playwright验收记录');
  await submit(box, '保存规则版本');
  assert.equal(await page.locator('tbody tr').count(), 5);
  assert.equal(await page.getByText('v1 · 当前', { exact: true }).count(), 5);
  results.push('新增同类内部规则后五条规则并存，不覆盖原四条');
  await capture('05-rules');
  await page.goto(`${base}/#/receipts?project=${projectId}`);
  await page.getByRole('log', { name: '真实任务事件流' }).waitFor();
  await page.getByText('当前范围暂无执行事件；不会生成模拟进度。', { exact: true }).waitFor();
  assert.equal(await page.getByText('Web 发起单任务验证', { exact: true }).count(), 0);
  results.push('任务中心使用真实空态，无模拟事件；诊断入口不混入正式任务');
  await capture('06-tasks');
  await page.goto(`${base}/#/exceptions?project=${projectId}`);
  await page.getByRole('heading', { name: '需处理的任务与人工待办', exact: true }).waitFor();
  await capture('07-exceptions');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto(`${base}/#/clients?object=${projectId}&project=${projectId}`);
  await page.getByRole('heading', { name: project, exact: true }).waitFor();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'mobile page must not overflow horizontally');
  await capture('08-mobile-project');
  results.push('390px 移动布局无页面级横向溢出');
  // Archive the test project using the same ordinary user operation, retaining audit records.
  box = await form('结束服务合作');
  await box.getByLabel('结束原因').fill('Playwright本地验收完成；没有真机绑定、设备任务或公开发布');
  await box.getByRole('button', { name: '确认退出并撤销关联授权', exact: true }).click();
  await box.waitFor({ state: 'detached' });
  await page.getByText('已退出', { exact: true }).first().waitFor();
  results.push('测试项目通过 Web 退出归档，测试授权撤销，历史记录保留');
  assert.deepEqual(errors, []);
} catch (error) {
  await capture('failure');
  throw error;
} finally {
  await writeFile(resolve(output, 'results.json'), JSON.stringify({ checkedAt: new Date().toISOString(), base, project, account, results, pageErrors: errors, publicationAttempted: false, identityCreationAttempted: false }, null, 2), { mode: 0o600 });
  console.log(JSON.stringify({ results, pageErrors: errors, project, output }, null, 2));
  await browser.close();
}
