import assert from "node:assert/strict";
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { chromium } from "playwright";
const base = process.env.SG_WEB_BASE_URL ?? "http://127.0.0.1:3100";
const output = resolve(process.env.SG_OPERATIONS_OUTPUT ?? "output/playwright/operations-complete");
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true }), checks: string[] = [];
const context = await browser.newContext({ locale: "zh-CN", viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
const writes: { path: string; body: string }[] = [], errors: string[] = [];
page.on("pageerror", error => errors.push(error.message));
page.on("request", request => {
  const path = new URL(request.url()).pathname;
  if (["POST", "PUT", "PATCH", "DELETE"].includes(request.method()) && !/\/operator\/(login|logout)$/.test(path)) writes.push({ path, body: request.postData() ?? "" });
});
const record = (check: string) => { checks.push(check); console.log(`[passed] ${check}`); };
let step = "login";
try {
  const password = process.env.SG_OPERATOR_PASSWORD ?? JSON.parse(await readFile(".runtime/product-local-live/config.json", "utf8")).operatorPassword;
  await page.goto(base, { waitUntil: "networkidle" });
  await page.getByLabel("登录名", { exact: true }).fill(process.env.SG_OPERATOR_LOGIN ?? "device-live-local");
  await page.getByLabel("密码", { exact: true }).fill(password);
  await page.getByRole("button", { name: "登录", exact: true }).click();
  await page.getByRole("button", { name: "项目", exact: true }).click();
  const workspace = page.locator(".project-workspace");
  await workspace.getByRole("button", { name: "打开项目", exact: true }).first().click();
  const projectName = await workspace.locator(".project-heading h1").innerText();
  step = "current-checks";
  await workspace.getByRole("button", { name: "排期与任务", exact: true }).click();
  const readiness = page.getByRole("region", { name: "计划任务当前条件", exact: true });
  await readiness.getByText("执行许可：关闭 · 发布许可：关闭", { exact: true }).waitFor();
  await readiness.getByText(/检查时间：/).waitFor();
  const rows = readiness.locator(".task-readiness__row"), taskCount = await rows.count();
  if (taskCount) {
    await rows.first().getByText(/项条件未通过或未知/).waitFor();
    for (let i = 0; i < taskCount; i++) assert.ok(await rows.nth(i).locator(".task-readiness__blocker").count());
  } else await readiness.getByText(/没有任务可核验，也不代表项目已就绪/).waitFor();
  record(`真实任务检查已加载：${taskCount} 项任务，明确阻断或无任务，许可关闭`);
  const currentPattern = "**/api/operator/projects/*/business-plan/current-checks";
  await page.route(currentPattern, route => route.abort("failed"));
  await readiness.getByRole("button", { name: "重新读取条件", exact: true }).click();
  await readiness.getByText(/当前条件读取失败，任务是否就绪未知/).waitFor();
  await readiness.getByText(/以下是历史检查结果/).waitFor();
  await page.unroute(currentPattern);
  await readiness.getByRole("button", { name: "重试读取", exact: true }).click();
  await readiness.getByText(/以下是历史检查结果/).waitFor({ state: "hidden" });
  record("任务检查读取中断后保留历史标识，重试恢复真实当前结果");
  await page.screenshot({ path: resolve(output, "08-task-readiness.png"), fullPage: true });
  step = "initialization-review";
  await workspace.getByRole("button", { name: "设置 · 目标与周期", exact: true }).click();
  const initialization = page.getByRole("region", { name: "发布身份初始化", exact: true });
  const reviewButton = initialization.getByRole("button", { name: "核验执行条件", exact: true }).first();
  await reviewButton.waitFor();
  await page.waitForFunction(() => Array.from(document.querySelectorAll('[aria-label="发布身份初始化"] button')).some(b => b.textContent === "核验执行条件" && !(b as HTMLButtonElement).disabled));
  assert.equal(await reviewButton.isEnabled(), true, "需要实际已有且已绑定资源的初始化任务，不能伪造成功状态");
  const reviewRow = initialization.getByRole("row").filter({ has: page.getByRole("button", { name: "核验执行条件", exact: true }) }).first();
  const taskLabel = await reviewRow.locator("td").first().innerText();
  const reviewPattern = "**/api/operator/projects/*/account-preparation/execution-review";
  // Abort the UI-originated request before it reaches the server. Do not inject a business result.
  await page.route(reviewPattern, route => route.abort("failed"));
  await reviewButton.click();
  await initialization.getByText(/本次请求结果尚未确认/).waitFor();
  assert.equal(await initialization.getByLabel("平台", { exact: true }).isDisabled(), true);
  await workspace.getByRole("button", { name: "排期与任务", exact: true }).click();
  await workspace.getByRole("button", { name: "设置 · 目标与周期", exact: true }).click();
  await initialization.getByRole("button", { name: "接续原初始化请求", exact: true }).waitFor();
  assert.equal(await initialization.getByLabel("平台", { exact: true }).isDisabled(), true);
  await page.unroute(reviewPattern);
  await initialization.getByRole("button", { name: "接续原初始化请求", exact: true }).click();
  await initialization.getByText("执行条件核验已记录；条件未满足，本次未派发手机动作。", { exact: true }).waitFor();
  assert.equal(writes.length, 2);
  assert.ok(writes.every(w => /\/account-preparation\/execution-review$/.test(w.path)));
  assert.equal(writes[0].body, writes[1].body, "网络失败后必须接续同一正文与幂等键");
  const detail = reviewRow.locator("details").filter({ has: page.getByText(/执行条件核验记录 · v/) });
  await detail.locator("summary").click();
  await detail.getByText(/核验时间：/).waitFor();
  await detail.getByText("本次核验未派发手机动作。", { exact: true }).waitFor();
  await detail.getByText(/可信证据核验链路接通/).waitFor();
  const receiptTime = await detail.getByText(/核验时间：/).innerText();
  record("初始化核验经真实页面接续原请求并保存阻断回执，无手机派发");
  await page.screenshot({ path: resolve(output, "09-initialization-review.png"), fullPage: true });
  step = "persisted-review";
  await page.reload({ waitUntil: "networkidle" });
  await page.getByRole("button", { name: "项目", exact: true }).click();
  await workspace.getByRole("row").filter({ hasText: projectName }).getByRole("button", { name: "打开项目", exact: true }).click();
  await workspace.getByRole("button", { name: "设置 · 目标与周期", exact: true }).click();
  const persistedRow = initialization.getByRole("row").filter({ has: page.getByRole("button", { name: "核验执行条件", exact: true }) }).first();
  assert.equal(await persistedRow.locator("td").first().innerText(), taskLabel);
  const persistedDetail = persistedRow.locator("details").filter({ has: page.getByText(/执行条件核验记录 · v/) });
  await persistedDetail.locator("summary").click();
  await persistedDetail.getByText(receiptTime, { exact: true }).waitFor();
  await persistedDetail.getByText("本次核验未派发手机动作。", { exact: true }).waitFor();
  assert.equal(writes.length, 2, "重载页面只读取，不重发写入");
  record("完整刷新后同一任务核验时间与阻断回执仍存在，未重发请求");
  step = "resource-navigation";
  await initialization.getByRole("button", { name: "核对手机当前状态", exact: true }).click();
  await page.getByRole("heading", { name: "手机资源", exact: true }).waitFor();
  await page.getByRole("button", { name: "项目", exact: true }).click();
  await initialization.getByRole("button", { name: "核对项目账号与手机分配", exact: true }).click();
  await page.locator(".media-accounts-workspace").waitFor();
  record("初始化的手机状态与项目账号分配入口实际可达");
  step = "mobile";
  await page.getByRole("button", { name: "项目", exact: true }).click();
  await workspace.getByRole("button", { name: "排期与任务", exact: true }).click();
  await readiness.getByText("执行许可：关闭 · 发布许可：关闭", { exact: true }).waitFor();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByText("手机端为只读模式", { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true);
  await page.screenshot({ path: resolve(output, "10-task-readiness-mobile.png"), fullPage: true });
  record("390px任务条件可读且没有整页横向溢出");
  assert.deepEqual(errors, []);
  await writeFile(resolve(output, "completion-result.json"), JSON.stringify({ result: "passed", base, checks, businessWrites: 2, serverReachingBusinessWrites: 1, scope: "原初始化任务执行条件核验；无设备派发、模型调用、公开发布", unexpectedBrowserErrors: errors.length }, null, 2));
} catch (error) {
  await page.screenshot({ path: resolve(output, "completion-failure.png"), fullPage: true }).catch(() => undefined);
  await writeFile(resolve(output, "completion-result.json"), JSON.stringify({ result: "failed", step, checks, error: error instanceof Error ? error.message : "unexpected", businessWriteAttempts: writes.length }, null, 2));
  throw error;
} finally { await context.close(); await browser.close(); }
