import assert from "node:assert/strict";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { chromium } from "playwright";
const baseUrl = process.env.SG_WEB_BASE_URL ?? "http://127.0.0.1:3100";
const outputDir = resolve(process.env.SG_OPERATIONS_OUTPUT ?? "output/playwright/operations-fix");
await mkdir(outputDir, { recursive: true });
const checks: string[] = [];
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ locale: "zh-CN", viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
let activeStep = "login", nonLoginWrites = 0;
page.on("request", request => { if (["POST", "PUT", "PATCH", "DELETE"].includes(request.method()) && !/\/operator\/(login|logout)$/.test(new URL(request.url()).pathname)) nonLoginWrites++; });
const record = (check: string) => { checks.push(check); console.log(`[passed] ${check}`); };
try {
  const password = process.env.SG_OPERATOR_PASSWORD ?? (JSON.parse(await readFile(".runtime/product-local-live/config.json", "utf8")) as { operatorPassword: string }).operatorPassword;
  await page.goto(baseUrl, { waitUntil: "networkidle" });
  await page.getByRole("heading", { name: "登录正式产品", exact: true }).waitFor();
  await page.getByLabel("登录名", { exact: true }).fill(process.env.SG_OPERATOR_LOGIN ?? "device-live-local");
  await page.getByLabel("密码", { exact: true }).fill(password);
  await page.getByRole("button", { name: "登录", exact: true }).click();

  const home = page.getByRole("region", { name: "运营工作台", exact: true });
  await home.getByRole("heading", { name: "项目运营入口", exact: true }).waitFor();
  await home.getByRole("button", { name: "打开项目", exact: true }).first().waitFor();
  assert.equal(await page.getByRole("button", { name: "工作台", exact: true }).isEnabled(), true);
  record("登录默认进入可操作工作台，真实项目与全局待办加载");
  await page.screenshot({ path: resolve(outputDir, "01-workbench.png"), fullPage: true });
  activeStep = "project-overview";
  await home.getByRole("button", { name: "打开项目", exact: true }).first().click();
  const workspace = page.locator(".project-workspace");
  const overview = page.getByRole("region", { name: "项目当前事实", exact: true });
  await overview.getByRole("button", { name: "刷新项目状态", exact: true }).waitFor();
  await page.waitForFunction(() => !document.querySelector('[aria-label="项目当前事实"] button[disabled]'));
  assert.equal(await overview.getByText("分配事实未知。", { exact: true }).count(), 0, "正常环境分配事实必须加载");
  const resourceNames = await overview.locator("li > strong").allTextContents();
  assert.ok(resourceNames.every(name => name !== "账号名称未知"), "已分配账号应有可读名称");
  const projectName = await workspace.locator(".project-heading h1").innerText();
  record("项目概览读取持久账号手机分配，显示真实下一步");
  await page.screenshot({ path: resolve(outputDir, "02-project-overview.png"), fullPage: true });
  activeStep = "resources";
  await overview.getByRole("button", { name: "查看或分配媒体账号与手机", exact: true }).click();
  const media = page.locator(".media-accounts-workspace");
  await media.waitFor();
  for (const name of resourceNames) await media.getByText(name, { exact: true }).first().waitFor();
  record("概览资源入口可达，账号名称与媒体账号页面一致");
  await page.getByRole("button", { name: "项目", exact: true }).click();
  // Project panel keeps the selected project across main navigation.
  await workspace.getByRole("button", { name: "AI 自动化总控", exact: true }).click();
  const control = page.getByRole("region", { name: "AI 自动化总控", exact: true });
  await control.getByRole("heading", { name: "AI 自动化调度总控", exact: true }).waitFor();
  await control.getByText("执行与公开发布许可关闭；不能启动手机发布", { exact: true }).waitFor();
  const text = await control.innerText();
  assert.ok(!/95%|5%|发布已成功|恢复已成功|推演思维链|Samsung|Tongm/.test(text));
  assert.equal(await control.getByRole("button", { name: /开始闭环|模拟异常|恢复执行/ }).count(), 0);
  record("总控读取真实门禁，无固定成功回执、假AI或计时器执行入口");
  await page.screenshot({ path: resolve(outputDir, "03-orchestrator.png"), fullPage: true });
  activeStep = "real-navigation";
  await control.getByRole("button", { name: "核对排期与任务", exact: true }).click();
  await page.getByRole("heading", { name: "排期与任务", exact: true }).waitFor();
  assert.equal(await workspace.locator(".project-heading h1").innerText(), projectName);
  await workspace.getByRole("button", { name: "AI 自动化总控", exact: true }).click();
  await control.getByRole("button", { name: "前往目标与方向", exact: true }).click();
  const direction = page.getByRole("region", { name: "初始业务方向", exact: true });
  await direction.getByLabel("发布平台 1", { exact: true }).waitFor();
  await direction.getByLabel("发布平台 1", { exact: true }).selectOption("facebook");
  await direction.getByLabel("发布身份编号 1", { exact: true }).fill("ops_review_identity");
  await direction.getByLabel("分成资格阶段 1", { exact: true }).selectOption("before_monetization");
  await direction.getByRole("button", { name: "添加发布身份", exact: true }).click();
  await direction.getByLabel("发布平台 2", { exact: true }).selectOption("youtube");
  await direction.getByLabel("发布身份编号 2", { exact: true }).fill("ops_review_channel");
  await direction.getByLabel("分成资格阶段 2", { exact: true }).selectOption("after_monetization");
  await direction.getByRole("button", { name: "移除发布身份 2", exact: true }).click();
  assert.equal(await direction.getByLabel("发布身份编号 1", { exact: true }).inputValue(), "ops_review_identity");
  await direction.getByLabel("发布身份编号 1", { exact: true }).fill("invalid/reference");
  await direction.getByRole("button", { name: "生成初始方向", exact: true }).click();
  await direction.getByText(/输入或版本不满足要求/).waitFor();
  await direction.getByLabel("发布身份编号 1", { exact: true }).fill("ops_review_identity");
  record("结构化范围提交校验拒绝无效编号，保留输入且不调用模型");
  const initialization = page.getByRole("region", { name: "发布身份初始化", exact: true });
  await initialization.getByLabel("项目账号", { exact: true }).waitFor();
  for (const name of resourceNames) assert.ok((await initialization.getByLabel("项目账号", { exact: true }).innerText()).includes(name));
  record("真实排期/设置入口保持项目，结构化身份范围可增删且资源选择显示名称");
  await page.screenshot({ path: resolve(outputDir, "04-structured-settings.png"), fullPage: true });
  activeStep = "feedback-lifecycle-todos";
  await workspace.getByRole("button", { name: "效果与复盘", exact: true }).click();
  await page.getByRole("heading", { name: "效果与复盘", exact: true }).waitFor();
  const feedback = page.getByRole("region", { name: "项目效果与复盘", exact: true });
  await feedback.getByRole("heading", { name: "效果快照", exact: true }).waitFor();
  const metricCards = feedback.locator(".project-feedback__metric");
  for (let i = 0; i < await metricCards.count(); i++) {
    await metricCards.nth(i).getByRole("heading", { name: "指标名称未提供", exact: true }).waitFor();
    await metricCards.nth(i).getByText("来源未提供单位", { exact: true }).waitFor();
    assert.equal(await metricCards.nth(i).getByText(/定义编号/).isVisible(), false, "记录编号应位于可展开详情中");
  }
  await page.screenshot({ path: resolve(outputDir, "07-feedback.png"), fullPage: true });
  await workspace.getByRole("button", { name: "项目生命周期", exact: true }).click();
  assert.equal(await workspace.getByRole("heading", { name: "基本信息", exact: true }).isVisible(), false);
  await workspace.getByRole("button", { name: "AI 自动化总控", exact: true }).click();
  await control.getByRole("button", { name: "查看设备接入待办", exact: true }).click();
  await page.getByRole("heading", { name: "设备接入待办", exact: true }).first().waitFor();
  record("效果/生命周期/协助入口可达，生命周期不再被基本信息表单遮挡");
  activeStep = "failure-and-retry";
  await page.getByRole("button", { name: "项目", exact: true }).click();
  await workspace.getByRole("button", { name: "AI 自动化总控", exact: true }).click();
  const failPattern = "**/api/operator/projects/*/business-plan";
  // Transport failure only: no fake business result, no DB setup or API mutation.
  await page.route(failPattern, route => route.abort("failed"));
  await control.getByRole("button", { name: "刷新项目事实", exact: true }).click();
  await control.getByText("计划事实未知", { exact: true }).waitFor();
  await control.getByText("执行许可未知；不能启动", { exact: true }).waitFor();
  record("真实入口遭遇传输失败时显示未知，不会变成0任务或就绪");
  await page.screenshot({ path: resolve(outputDir, "05-source-failure.png"), fullPage: true });
  await page.unroute(failPattern);
  await control.getByRole("button", { name: "刷新项目事实", exact: true }).click();
  await control.getByText("执行与公开发布许可关闭；不能启动手机发布", { exact: true }).waitFor();
  record("解除传输故障后通过刷新读取真实状态");
  activeStep = "mobile";
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByText("手机端为只读模式", { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), true, "页面不应整体横向溢出，表格可内部滚动");
  await page.screenshot({ path: resolve(outputDir, "06-mobile.png"), fullPage: true });
  record("手机端保留只读说明，无整页横向溢出");
  activeStep = "session-expiry";
  await page.setViewportSize({ width: 1440, height: 1000 });
  // Actual logout in the same authenticated browser session expires the original page.
  const popup = page.waitForEvent("popup"); await page.evaluate(url => { window.open(url); }, baseUrl); const other = await popup; await other.waitForLoadState("networkidle");
  await other.getByRole("button", { name: "退出登录", exact: true }).first().click();
  await other.getByRole("heading", { name: "登录正式产品", exact: true }).waitFor();
  await control.getByRole("button", { name: "刷新项目事实", exact: true }).click();
  await page.getByRole("heading", { name: "登录正式产品", exact: true }).waitFor();
  await other.close();
  record("服务端实际会话过期401后清除工作区并回到登录");
  assert.equal(nonLoginWrites, 0, "本回归不派发模型、初始化、暂停或发布写入");
  await writeFile(resolve(outputDir, "result.json"), JSON.stringify({ result: "passed", baseUrl, checks, businessWrites: nonLoginWrites, boundaries: ["当前候选Web操作与读取验证通过", "仅传输故障注入，无模拟业务成功", "未调用模型、手机或公开发布", "不证明自动发布或人工恢复闭环"] }, null, 2));
} catch (error) {
  await page.screenshot({ path: resolve(outputDir, "failure.png"), fullPage: true }).catch(() => undefined);
  await writeFile(resolve(outputDir, "result.json"), JSON.stringify({ result: "failed", activeStep, checks, error: error instanceof Error ? error.message : "unexpected error", boundaries: ["不证明模型、手机、公开发布或恢复成功"] }, null, 2));
  throw error;
} finally { await context.close(); await browser.close(); }
